//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 01:39:22 CEST 
//


package com.gentics.lib.formatter.dateformatter;


/**
 * Java content class for date-formats element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/date-format.xsd line 18)
 * <p>
 * <pre>
 * &lt;element name="date-formats" type="{}dateFormatsType"/>
 * </pre>
 * 
 */
public interface DateFormats
    extends javax.xml.bind.Element, com.gentics.lib.formatter.dateformatter.JAXBdateFormatsType
{


}
