//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.25 at 01:39:22 CEST 
//


package com.gentics.lib.formatter.dateformatter;


/**
 * Java content class for dateFormatsType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/date-format.xsd line 21)
 * <p>
 * <pre>
 * &lt;complexType name="dateFormatsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="date-format" type="{}dateFormatType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="default" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JAXBdateFormatsType {


    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDefault();

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDefault(java.lang.String value);

    boolean isSetDefault();

    void unsetDefault();

    /**
     * 
     * @return
     *     array of
     *     {@link com.gentics.lib.formatter.dateformatter.JAXBdateFormatType}
     */
    com.gentics.lib.formatter.dateformatter.JAXBdateFormatType[] getDateFormat();

    /**
     * 
     * @return
     *     one of
     *     {@link com.gentics.lib.formatter.dateformatter.JAXBdateFormatType}
     */
    com.gentics.lib.formatter.dateformatter.JAXBdateFormatType getDateFormat(int idx);

    int getDateFormatLength();

    /**
     * 
     * @param values
     *     allowed objects are
     *     {@link com.gentics.lib.formatter.dateformatter.JAXBdateFormatType}
     */
    void setDateFormat(com.gentics.lib.formatter.dateformatter.JAXBdateFormatType[] values);

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.gentics.lib.formatter.dateformatter.JAXBdateFormatType}
     */
    com.gentics.lib.formatter.dateformatter.JAXBdateFormatType setDateFormat(int idx, com.gentics.lib.formatter.dateformatter.JAXBdateFormatType value);

    boolean isSetDateFormat();

    void unsetDateFormat();

}
