//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:30 CEST 
//


package com.gentics.lib.datasource.object.jaxb.impl;

public class JAXBVersion {

    public final static java.lang.String version = "1.0.4";

}
