import { SharedModule } from '@admin-ui/shared/shared.module';
import { CommonModule } from '@angular/common';
import { NgModule, Provider, Type } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import {
    CopyTokenModal,
    CopyValueComponent,
    LoginGateComponent,
    ManageTagFamiliesModal,
    ManagementComponent,
    ManagementTabsComponent,
    MeshGroupModal,
    MeshGroupPropertiesComponent,
    MeshGroupTableComponent,
    MeshRoleModal,
    MeshRolePermissionsEditModal,
    MeshRolePermissionsModal,
    MeshRolePermissionsTrableComponent,
    MeshRolePropertiesComponent,
    MeshRoleTableComponent,
    MeshUserModal,
    MeshUserPropertiesComponent,
    MeshUserTableComponent,
    MicroschemaModal,
    MicroschemaPropertiesComponent,
    MicroschemaTableComponent,
    ProjectModal,
    ProjectPropertiesComponent,
    ProjectTableComponent,
    SchemaFieldPropertiesComponent,
    SchemaFieldsManagerComponent,
    SchemaModal,
    SchemaPickerComponent,
    SchemaPropertiesComponent,
    SchemaTableComponent,
    SelectGroupModal,
    SelectMicroschemaModal,
    SelectProjectModal,
    SelectRoleModal,
    SelectSchemaModal,
    SelectTagFamilyModal,
    SelectTagModal,
    SelectUserModal,
    ServerOverviewComponent,
    TagFamilyModal,
    TagFamilyPropertiesComponent,
    TagFamilyTableComponent,
    TagModal,
    TagPropertiesComponent,
    TagTableComponent,
} from './components';
import { MeshIconPipe } from './pipes';
import {
    MeshGroupHandlerService,
    MeshGroupTableLoaderService,
    MeshNodeHandlerService,
    MeshRoleHandlerService,
    MeshRolePermissionHandlerService,
    MeshRolePermissionsTrableLoaderService,
    MeshRoleTableLoaderService,
    MeshUserHandlerService,
    MeshUserTableLoaderService,
    MicroschemaHandlerService,
    MicroschemaTableLoaderService,
    ProjectHandlerService,
    ProjectTableLoaderService,
    SchemaHandlerService,
    SchemaTableLoaderService,
    TagFamilyHandlerService,
    TagFamilyTableLoaderService,
    TagHandlerService,
    TagTableLoaderService,
} from './providers';

const COMPONENTS: Type<any>[] = [
    CopyTokenModal,
    CopyValueComponent,
    LoginGateComponent,
    ManageTagFamiliesModal,
    ManagementComponent,
    ManagementTabsComponent,
    MeshGroupModal,
    MeshGroupPropertiesComponent,
    MeshGroupTableComponent,
    MeshRoleModal,
    MeshRolePermissionsEditModal,
    MeshRolePermissionsModal,
    MeshRolePermissionsTrableComponent,
    MeshRoleTableComponent,
    MeshRolePropertiesComponent,
    MeshUserModal,
    MeshUserPropertiesComponent,
    MeshUserTableComponent,
    MicroschemaModal,
    MicroschemaPropertiesComponent,
    MicroschemaTableComponent,
    ProjectModal,
    ProjectPropertiesComponent,
    ProjectTableComponent,
    SchemaFieldPropertiesComponent,
    SchemaFieldsManagerComponent,
    SchemaModal,
    SchemaPickerComponent,
    SchemaPropertiesComponent,
    SchemaTableComponent,
    SelectGroupModal,
    SelectMicroschemaModal,
    SelectProjectModal,
    SelectRoleModal,
    SelectSchemaModal,
    SelectTagFamilyModal,
    SelectTagModal,
    SelectUserModal,
    ServerOverviewComponent,
    TagFamilyModal,
    TagFamilyPropertiesComponent,
    TagFamilyTableComponent,
    TagModal,
    TagPropertiesComponent,
    TagTableComponent,
];

const PIPES: Type<any>[] = [
    MeshIconPipe,
];

const DECLARATIONS = [
    ...COMPONENTS,
    ...PIPES,
];

const SERVICES: Provider[] = [
    MeshGroupHandlerService,
    MeshGroupTableLoaderService,
    MeshNodeHandlerService,
    MeshRoleHandlerService,
    MeshRolePermissionHandlerService,
    MeshRolePermissionsTrableLoaderService,
    MeshRoleTableLoaderService,
    MeshUserHandlerService,
    MeshUserTableLoaderService,
    MicroschemaHandlerService,
    MicroschemaTableLoaderService,
    ProjectHandlerService,
    ProjectTableLoaderService,
    SchemaHandlerService,
    SchemaTableLoaderService,
    TagFamilyHandlerService,
    TagFamilyTableLoaderService,
    TagHandlerService,
    TagTableLoaderService,
];

@NgModule({
    id: 'admin-ui_mesh',
    declarations: DECLARATIONS,
    providers: [
        ...SERVICES,
    ],
    exports: DECLARATIONS,
    imports: [
        CommonModule,
        FormsModule,
        ReactiveFormsModule,
        RouterModule.forChild([]),
        SharedModule,
    ],
})
export class MeshModule { }
