query ($languages: [String]) {
  schema(name: "%s") {
    nodes(perPage: %d, page: %d, lang: $languages) {
      hasNextPage
      elements {
        uuid
        parent {
          uuid
        }
        languages {
          language
        }
      }
    }
  }
}
