{
  schema(name: "%s") {
    nodes(perPage: %d, page: %d) {
      hasNextPage
      elements {
        uuid
        languages {
          language
          fields {
            ... on %s {
              cms_id
            }
          }
        }
      }
    }
  }
}
