<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.gentics</groupId>
        <artifactId>cms-oss</artifactId>
        <version>ci-devtest-SNAPSHOT</version>
    </parent>

    <groupId>com.gentics.cms-oss</groupId>
    <artifactId>cms-ui</artifactId>
    <packaging>pom</packaging>

    <name>Gentics CMS UI</name>
    <description>This is the Gentics CMS UI monorepo module</description>
    <url>http://www.gentics.com</url>

    <properties>
        <!-- If the UI module should skip the assembly step -->
        <ui.skip.assembly>false</ui.skip.assembly>
        <!-- If the UI module should skip reporting -->
        <ui.skip.report>false</ui.skip.report>
    </properties>

    <build>
        <plugins>
            <plugin>
				<artifactId>maven-assembly-plugin</artifactId>

				<executions>
                    <execution>
						<id>apps</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
                            <skipAssembly>${ui.skip.assembly}</skipAssembly>
							<attach>true</attach>
							<appendAssemblyId>false</appendAssemblyId>
							<descriptors>
								<descriptor>${project.basedir}/assembly/apps.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>

					<execution>
						<id>docs</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
                            <skipAssembly>${ui.skip.assembly}</skipAssembly>
							<attach>true</attach>
							<appendAssemblyId>true</appendAssemblyId>
							<descriptors>
								<descriptor>${project.basedir}/assembly/docs.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>

                    <execution>
						<id>custom-tools</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
                            <skipAssembly>${ui.skip.assembly}</skipAssembly>
							<attach>true</attach>
							<appendAssemblyId>true</appendAssemblyId>
							<descriptors>
								<descriptor>${project.basedir}/assembly/custom-tools.xml</descriptor>
							</descriptors>
						</configuration>
					</execution>

                    <execution>
                        <id>make-report-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <skipAssembly>${ui.skip.report}</skipAssembly>
                            <appendAssemblyId>true</appendAssemblyId>
                            <descriptors>
                                <descriptor>report-assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>com.gentics</groupId>
                <artifactId>dependency-reporting-plugin</artifactId>

                <executions>
                    <execution>
                        <id>npm-transform</id>
                        <goals>
                            <goal>npm-transform</goal>
                        </goals>
                        <phase>process-resources</phase>

                        <configuration>
                            <skip>${ui.skip.report}</skip>
                            <dependenciesFile>${project.basedir}/prepared_dependencies.json</dependenciesFile>
                            <outdatedFile>${project.basedir}/outdated_dependencies.json</outdatedFile>
                            <componentName>CMS OSS</componentName>
                            <moduleName>User Interface</moduleName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
