import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { CmsComponentsModule } from '@gentics/cms-components';
import { GenticsUICoreModule } from '@gentics/ui-core';
import { PackageCheckTrableLoaderService } from '@admin-ui/core';
import {
    AccordionComponent,
    AssignCRFragmentsToContentRepositoryModal,
    AssignContentrepositoriesToNodesModalComponent,
    AssignEntityToPackageModalComponent,
    AssignGroupToUsersModalComponent,
    AssignNodeRestrictionsToObjectPropertiesModalComponent,
    AssignNodeRestrictionsToUsersModalComponent,
    AssignPackagesToNodeModalComponent,
    AssignUserToGroupsModalComponent,
    BooleanIconComponent,
    ConfirmDeleteModalComponent,
    ConfirmRemoveUserFromGroupModalComponent,
    ConstructTableComponent,
    ContentRepositoryTableComponent,
    CreateContentRepositoryFragmentModalComponent,
    CreateDataSourceEntryModalComponent,
    CreateDataSourceModalComponent,
    CreateGroupModalComponent,
    CreateLanguageModalComponent,
    CreateUpdateTagmapEntryModalComponent,
    CreateUserModalComponent,
    CRFragmentTableComponent,
    DataSourceEntryTableComponent,
    DataSourceTableComponent,
    DevToolPackageTableComponent,
    EditPermissionsModalComponent,
    EntityDetailHeaderComponent,
    EntityPickerComponent,
    EntityPickerModalComponent,
    FolderTrableComponent,
    GenericRouterOutletComponent,
    GroupTableComponent,
    GroupTrableComponent,
    IconCheckboxComponent,
    IconComponent,
    LanguageTableComponent,
    LoadingOverlayComponent,
    LoadingTriggerComponent,
    LoadingWrapperComponent,
    MaintenanceModeIndicatorComponent,
    MoveGroupsModalComponent,
    NodeTableComponent,
    ObjectPropertyTableComponent,
    PermissionIconComponent,
    PackageCheckTrableComponent,
    PermissionsTrableComponent,
    PropertiesManagerComponent,
    PropertiesTabsComponent,
    SendMessageFormComponent,
    SendMessageModalComponent,
    SidebarItemComponent,
    SidebarItemGroupComponent,
    SplitViewRouterOutletComponent,
    TagEditorWrapperComponent,
    TagMapEntryPropertiesComponent,
    TagMapEntryTableComponent,
    TemplateFolderLinkTrableComponent,
    TemplateTableComponent,
    UserTableComponent,
    WidgetPublishingProcessComponent,
    WidgetPublishingProcessTotalComponent,
    WizardComponent,
    WizardModalComponent,
    I18nPanelGroupComponent,
} from './components';
import { ContentItemTrableComponent } from './components/content-item-trable/content-item-trable.component';
import {
    ActionAllowedDirective,
    DetailTabLinkDirective,
    WizardStepDirective,
} from './directives';
import {
    CountRolesPipe,
    EntityDetailRouterLinkPipe,
    EntityNamePipe,
    I18nNumberPipe,
    I18nRelativeDatePipe,
} from './pipes';
import {
    ConstructCategoryDataService,
    ConstructDataService,
    ContentItemTrableLoaderService,
    ContentPackageDataService,
    ContentRepositoryDataService,
    ContentRepositoryFragmentDataService,
    ContentRepositoryTagmapEntryDataService,
    ContextMenuService,
    DataSourceConstructDataService,
    DataSourceDataService,
    DataSourceEntryDataService,
    EntityExistsValidator,
    FolderDataService,
    GroupDataService,
    GroupUserDataService,
    I18nRelativeDateService,
    LanguageDataService,
    MarkupLanguageDataService,
    NodeDataService,
    NodePackageDataService,
    NotificationService,
    ObjectPropertyCategoryDataService,
    ObjectPropertyDataService,
    PackageDataService,
    RoleDataService,
    ScheduleDataService,
    ScheduleExecutionDataService,
    ScheduleTaskDataService,
    SubgroupDataService,
    TemplateDataService,
    TemplateTagDataService,
    TemplateTagStatusDataService,
    UserDataService,
    UserGroupDataService,
    WizardService,
} from './providers';

const COMPONENTS: any[] = [
    AccordionComponent,
    AssignCRFragmentsToContentRepositoryModal,
    AssignContentrepositoriesToNodesModalComponent,
    AssignEntityToPackageModalComponent,
    AssignGroupToUsersModalComponent,
    AssignNodeRestrictionsToObjectPropertiesModalComponent,
    AssignNodeRestrictionsToUsersModalComponent,
    AssignPackagesToNodeModalComponent,
    AssignUserToGroupsModalComponent,
    BooleanIconComponent,
    ConfirmDeleteModalComponent,
    ConfirmRemoveUserFromGroupModalComponent,
    ConstructTableComponent,
    PackageCheckTrableComponent,
    PermissionsTrableComponent,
    ContentRepositoryTableComponent,
    ContentItemTrableComponent,
    CRFragmentTableComponent,
    CreateContentRepositoryFragmentModalComponent,
    CreateDataSourceEntryModalComponent,
    CreateDataSourceModalComponent,
    CreateGroupModalComponent,
    CreateLanguageModalComponent,
    CreateUpdateTagmapEntryModalComponent,
    CreateUserModalComponent,
    DataSourceEntryTableComponent,
    DataSourceTableComponent,
    DevToolPackageTableComponent,
    EditPermissionsModalComponent,
    EntityDetailHeaderComponent,
    EntityPickerComponent,
    EntityPickerModalComponent,
    FolderTrableComponent,
    GenericRouterOutletComponent,
    GroupTableComponent,
    GroupTrableComponent,
    I18nPanelGroupComponent,
    IconCheckboxComponent,
    IconComponent,
    LanguageTableComponent,
    LoadingOverlayComponent,
    LoadingTriggerComponent,
    LoadingWrapperComponent,
    MaintenanceModeIndicatorComponent,
    MoveGroupsModalComponent,
    NodeTableComponent,
    ObjectPropertyTableComponent,
    PermissionIconComponent,
    PropertiesManagerComponent,
    PropertiesTabsComponent,
    SendMessageFormComponent,
    SendMessageModalComponent,
    SidebarItemComponent,
    SidebarItemGroupComponent,
    SplitViewRouterOutletComponent,
    TagEditorWrapperComponent,
    TagMapEntryTableComponent,
    TagMapEntryPropertiesComponent,
    TemplateFolderLinkTrableComponent,
    TemplateTableComponent,
    UserTableComponent,
    WidgetPublishingProcessComponent,
    WidgetPublishingProcessTotalComponent,
    WizardComponent,
    WizardModalComponent,
];

const DIRECTIVES = [
    ActionAllowedDirective,
    DetailTabLinkDirective,
    WizardStepDirective,
];

const PIPES: any[] = [
    CountRolesPipe,
    EntityDetailRouterLinkPipe,
    EntityNamePipe,
    I18nNumberPipe,
    I18nRelativeDatePipe,
];

const DECLARATIONS: any[] = [
    ...COMPONENTS,
    ...DIRECTIVES,
    ...PIPES,
];

const PROVIDERS: any[] = [
    ConstructDataService,
    ConstructCategoryDataService,
    ContentItemTrableLoaderService,
    ContentPackageDataService,
    ContentRepositoryDataService,
    ContentRepositoryFragmentDataService,
    ContentRepositoryTagmapEntryDataService,
    ContextMenuService,
    DataSourceConstructDataService,
    DataSourceDataService,
    DataSourceEntryDataService,
    EntityExistsValidator,
    FolderDataService,
    GroupDataService,
    GroupUserDataService,
    I18nRelativeDateService,
    LanguageDataService,
    MarkupLanguageDataService,
    NodeDataService,
    NodeDataService,
    NodePackageDataService,
    NotificationService,
    ObjectPropertyCategoryDataService,
    ObjectPropertyDataService,
    PackageDataService,
    PackageCheckTrableLoaderService,
    RoleDataService,
    ScheduleDataService,
    ScheduleExecutionDataService,
    ScheduleTaskDataService,
    SubgroupDataService,
    TemplateDataService,
    TemplateTagDataService,
    TemplateTagStatusDataService,
    UserDataService,
    UserGroupDataService,
    WizardService,
];

@NgModule({
    declarations: DECLARATIONS,
    imports: [
        CommonModule,
        FormsModule,
        GenticsUICoreModule.forRoot(),
        CmsComponentsModule,
        ReactiveFormsModule,
        RouterModule,
    ],
    exports: [
        CommonModule,
        FormsModule,
        GenticsUICoreModule,
        CmsComponentsModule,
        ReactiveFormsModule,
        ...DECLARATIONS,
    ],
    providers: PROVIDERS,
})
export class SharedModule { }
