/* Generated By:JJTree: Do not edit this line. ASTAnd.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTAnd extends FunctionNode {
	public ASTAnd(int id) {
		super(id);
	}

	public ASTAnd(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getAndFunction();
	}

	protected int getType() {
		return Function.TYPE_AND;
	}
}
