/* Generated By:JJTree: Do not edit this line. ASTContainsnone.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTContainsnone extends FunctionNode {
	public ASTContainsnone(int id) {
		super(id);
	}

	public ASTContainsnone(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getContainsNoneFunction();
	}

	protected int getType() {
		return Function.TYPE_CONTAINSNONE;
	}
}
