/* Generated By:JJTree: Do not edit this line. ASTContainsoneof.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTContainsoneof extends FunctionNode {
	public ASTContainsoneof(int id) {
		super(id);
	}

	public ASTContainsoneof(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getContainsOneOfFunction();
	}

	protected int getType() {
		return Function.TYPE_CONTAINSONEOF;
	}
}
