/* Generated By:JJTree: Do not edit this line. ASTDiv.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTDiv extends FunctionNode {
	public ASTDiv(int id) {
		super(id);
	}

	public ASTDiv(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getDivFunction();
	}

	protected int getType() {
		return Function.TYPE_DIV;
	}
}
