/* Generated By:JJTree: Do not edit this line. ASTEquals.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTEquals extends FunctionNode {
	public ASTEquals(int id) {
		super(id);
	}

	public ASTEquals(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getEqualFunction();
	}

	protected int getType() {
		return Function.TYPE_EQUAL;
	}
}
