/* Generated By:JJTree: Do not edit this line. ASTGreater.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTGreater extends FunctionNode {
	public ASTGreater(int id) {
		super(id);
	}

	public ASTGreater(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getGreaterFunction();
	}

	protected int getType() {
		return Function.TYPE_GREATER;
	}
}
