/* Generated By:JJTree: Do not edit this line. ASTGreaterOrEqual.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTGreaterOrEqual extends FunctionNode {
	public ASTGreaterOrEqual(int id) {
		super(id);
	}

	public ASTGreaterOrEqual(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getGreaterOrEqualFunction();
	}

	protected int getType() {
		return Function.TYPE_GREATEROREQUAL;
	}
}
