/* Generated By:JJTree: Do not edit this line. ASTMinus.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTMinus extends FunctionNode {
	public ASTMinus(int id) {
		super(id);
	}

	public ASTMinus(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getMinusFunction();
	}

	protected int getType() {
		return Function.TYPE_MINUS;
	}
}
