/* Generated By:JJTree: Do not edit this line. ASTMod.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTMod extends FunctionNode {
	public ASTMod(int id) {
		super(id);
	}

	public ASTMod(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getModFunction();
	}

	protected int getType() {
		return Function.TYPE_MOD;
	}
}
