/* Generated By:JJTree: Do not edit this line. ASTMult.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTMult extends FunctionNode {
	public ASTMult(int id) {
		super(id);
	}

	public ASTMult(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getMultFunction();
	}

	protected int getType() {
		return Function.TYPE_MULT;
	}
}
