/* Generated By:JJTree: Do not edit this line. ASTNot.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTNot extends FunctionNode {
	public ASTNot(int id) {
		super(id);
	}

	public ASTNot(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getNotFunction();
	}

	protected int getType() {
		return Function.TYPE_NOT;
	}
}
