/* Generated By:JJTree: Do not edit this line. ASTOr.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTOr extends FunctionNode {
	public ASTOr(int id) {
		super(id);
	}

	public ASTOr(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getOrFunction();
	}

	protected int getType() {
		return Function.TYPE_OR;
	}
}
