/* Generated By:JJTree: Do not edit this line. ASTSmaller.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTSmaller extends FunctionNode {
	public ASTSmaller(int id) {
		super(id);
	}

	public ASTSmaller(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getSmallerFunction();
	}

	protected int getType() {
		return Function.TYPE_SMALLER;
	}
}
