/* Generated By:JJTree: Do not edit this line. ASTUnequals.java */

package com.gentics.lib.expressionparser.parser;

import com.gentics.api.lib.expressionparser.functions.Function;
import com.gentics.lib.expressionparser.functions.AbstractFunctionRegistry.FunctionStore;

public class ASTUnequals extends FunctionNode {
	public ASTUnequals(int id) {
		super(id);
	}

	public ASTUnequals(Parser p, int id) {
		super(p, id);
	}

	protected Function getFunction(FunctionStore store) {
		return store.getUnequalFunction();
	}

	protected int getType() {
		return Function.TYPE_UNEQUAL;
	}
}
