/* Generated By:JJTree: Do not edit this line. .\ParserTreeConstants.java */

package com.gentics.lib.expressionparser.parser;

public interface ParserTreeConstants {
	public int JJTFUNCTION = 0;
	public int JJTNAME = 1;
	public int JJTSTATEMENT = 2;
	public int JJTVOID = 3;
	public int JJTASSIGNMENT = 4;
	public int JJTAND = 5;
	public int JJTOR = 6;
	public int JJTEQUALS = 7;
	public int JJTUNEQUALS = 8;
	public int JJTLIKE = 9;
	public int JJTCONTAINSONEOF = 10;
	public int JJTCONTAINSNONE = 11;
	public int JJTCONTAINSALL = 12;
	public int JJTSMALLER = 13;
	public int JJTGREATER = 14;
	public int JJTSMALLEROREQUAL = 15;
	public int JJTGREATEROREQUAL = 16;
	public int JJTADD = 17;
	public int JJTSUBTRACT = 18;
	public int JJTMULT = 19;
	public int JJTDIV = 20;
	public int JJTMOD = 21;
	public int JJTPLUS = 22;
	public int JJTMINUS = 23;
	public int JJTNOT = 24;
	public int JJTINTEGER = 25;
	public int JJTFLOAT = 26;
	public int JJTSTRING = 27;
	public int JJTARRAY = 28;
	public int JJTTRUE = 29;
	public int JJTFALSE = 30;
	public int JJTNULL = 31;

	public String[] jjtNodeName = {
		"Function", "Name", "Statement", "void", "Assignment", "And", "Or", "Equals", "Unequals", "Like", "Containsoneof", "Containsnone", "Containsall",
		"Smaller", "Greater", "SmallerOrEqual", "GreaterOrEqual", "Add", "Subtract", "Mult", "Div", "Mod", "Plus", "Minus", "Not", "Integer", "Float", "String",
		"Array", "True", "False", "Null",
	};
}
