/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package com.gentics.lib.expressionparser.parser;

public interface ParserConstants {

	int EOF = 0;
	int FALSE = 6;
	int NULL = 7;
	int TRUE = 8;
	int LIKE = 9;
	int CONTAINSONEOF = 10;
	int CONTAINSNONE = 11;
	int CONTAINSALL = 12;
	int AND = 13;
	int OR = 14;
	int INTEGER_LITERAL = 15;
	int DECIMAL_LITERAL = 16;
	int HEX_LITERAL = 17;
	int OCTAL_LITERAL = 18;
	int FLOATING_POINT_LITERAL = 19;
	int EXPONENT = 20;
	int CHARACTER_LITERAL = 21;
	int STRING_LITERAL = 22;
	int PATH = 23;
	int IDENTIFIER = 24;
	int SUBIDENTIFIER = 25;
	int LETTER = 26;
	int PART_LETTER = 27;
	int LPAREN = 28;
	int RPAREN = 29;
	int LBRACE = 30;
	int RBRACE = 31;
	int LBRACKET = 32;
	int RBRACKET = 33;
	int SEMICOLON = 34;
	int COMMA = 35;
	int DOT = 36;
	int ASSIGN = 37;
	int GT = 38;
	int LT = 39;
	int BANG = 40;
	int TILDE = 41;
	int HOOK = 42;
	int COLON = 43;
	int EQ = 44;
	int LE = 45;
	int GE = 46;
	int NE = 47;
	int SC_OR = 48;
	int SC_AND = 49;
	int INCR = 50;
	int DECR = 51;
	int PLUS = 52;
	int MINUS = 53;
	int STAR = 54;
	int SLASH = 55;
	int BIT_AND = 56;
	int BIT_OR = 57;
	int XOR = 58;
	int REM = 59;
	int LSHIFT = 60;
	int RSIGNEDSHIFT = 61;
	int RUNSIGNEDSHIFT = 62;
	int PLUSASSIGN = 63;
	int MINUSASSIGN = 64;
	int STARASSIGN = 65;
	int SLASHASSIGN = 66;
	int ANDASSIGN = 67;
	int ORASSIGN = 68;
	int XORASSIGN = 69;
	int REMASSIGN = 70;
	int LSHIFTASSIGN = 71;
	int RSIGNEDSHIFTASSIGN = 72;
	int RUNSIGNEDSHIFTASSIGN = 73;

	int DEFAULT = 0;

	String[] tokenImage = {
		"<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"\\f\"", "\"false\"", "\"null\"", "\"true\"", "\"LIKE\"", "\"CONTAINSONEOF\"", "\"CONTAINSNONE\"",
		"\"CONTAINSALL\"", "\"AND\"", "\"OR\"", "<INTEGER_LITERAL>", "<DECIMAL_LITERAL>", "<HEX_LITERAL>", "<OCTAL_LITERAL>", "<FLOATING_POINT_LITERAL>",
		"<EXPONENT>", "<CHARACTER_LITERAL>", "<STRING_LITERAL>", "<PATH>", "<IDENTIFIER>", "<SUBIDENTIFIER>", "<LETTER>", "<PART_LETTER>", "\"(\"", "\")\"",
		"\"{\"", "\"}\"", "\"[\"", "\"]\"", "\";\"", "\",\"", "\".\"", "\"=\"", "\">\"", "\"<\"", "\"!\"", "\"~\"", "\"?\"", "\":\"", "\"==\"", "\"<=\"",
		"\">=\"", "\"!=\"", "\"||\"", "\"&&\"", "\"++\"", "\"--\"", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\"&\"", "\"|\"", "\"^\"", "\"%\"", "\"<<\"", "\">>\"",
		"\">>>\"", "\"+=\"", "\"-=\"", "\"*=\"", "\"/=\"", "\"&=\"", "\"|=\"", "\"^=\"", "\"%=\"", "\"<<=\"", "\">>=\"", "\">>>=\"", "\"<>\"",
	};

}
