/* eslint-disable @typescript-eslint/naming-convention */
export enum Country {
    AFGHANISTAN = 'Afghanistan',
    ALBANIA = 'Albania',
    ALGERIA = 'Algeria',
    ANDORRA = 'Andorra',
    ANGOLA = 'Angola',
    ANTIGUA = 'Antigua',
    ARGENTINA = 'Argentina',
    ARMENIA = 'Armenia',
    AUSTRALIA = 'Australia',
    AUSTRIA = 'Austria',
    AZERBAIJAN = 'Azerbaijan',
    BAHAMAS = 'Bahamas',
    BAHRAIN = 'Bahrain',
    BANGLADESH = 'Bangladesh',
    BARBADOS = 'Barbados',
    BELARUS = 'Belarus',
    BELGIUM = 'Belgium',
    BELIZE = 'Belize',
    BENIN = 'Benin',
    BHUTAN = 'Bhutan',
    BOLIVIA = 'Bolivia',
    BOSNIA_HERZEGOVINA = 'Bosnia Herzegovina',
    BOTSWANA = 'Botswana',
    BRAZIL = 'Brazil',
    BRUNEI = 'Brunei',
    BULGARIA = 'Bulgaria',
    BURKINA = 'Burkina',
    BURUNDI = 'Burundi',
    CAMBODIA = 'Cambodia',
    CAMEROON = 'Cameroon',
    CANADA = 'Canada',
    CAPE_VERDE = 'Cape Verde',
    CENTRAL_AFRICAN_REP = 'Central African Rep',
    CHAD = 'Chad',
    CHILE = 'Chile',
    CHINA = 'China',
    COLOMBIA = 'Colombia',
    COMOROS = 'Comoros',
    CONGO = 'Congo',
    COSTA_RICA = 'Costa Rica',
    CROATIA = 'Croatia',
    CUBA = 'Cuba',
    CYPRUS = 'Cyprus',
    CZECH_REPUBLIC = 'Czech Republic',
    DENMARK = 'Denmark',
    DJIBOUTI = 'Djibouti',
    DOMINICA = 'Dominica',
    DOMINICAN_REPUBLIC = 'Dominican Republic',
    EAST_TIMOR = 'East Timor',
    ECUADOR = 'Ecuador',
    EGYPT = 'Egypt',
    EL_SALVADOR = 'El Salvador',
    EQUATORIAL_GUINEA = 'Equatorial Guinea',
    ERITREA = 'Eritrea',
    ESTONIA = 'Estonia',
    ETHIOPIA = 'Ethiopia',
    FIJI = 'Fiji',
    FINLAND = 'Finland',
    FRANCE = 'France',
    GABON = 'Gabon',
    GAMBIA = 'Gambia',
    GEORGIA = 'Georgia',
    GERMANY = 'Germany',
    GHANA = 'Ghana',
    GREECE = 'Greece',
    GRENADA = 'Grenada',
    GUATEMALA = 'Guatemala',
    GUINEA = 'Guinea',
    GUINEA_BISSAU = 'Guinea-Bissau',
    GUYANA = 'Guyana',
    HAITI = 'Haiti',
    HONDURAS = 'Honduras',
    HUNGARY = 'Hungary',
    ICELAND = 'Iceland',
    INDIA = 'India',
    INDONESIA = 'Indonesia',
    IRAN = 'Iran',
    IRAQ = 'Iraq',
    IRELAND = 'Ireland',
    ISRAEL = 'Israel',
    ITALY = 'Italy',
    IVORY_COAST = 'Ivory Coast',
    JAMAICA = 'Jamaica',
    JAPAN = 'Japan',
    JORDAN = 'Jordan',
    KAZAKHSTAN = 'Kazakhstan',
    KENYA = 'Kenya',
    KIRIBATI = 'Kiribati',
    KOREA_NORTH = 'Korea North',
    KOREA_SOUTH = 'Korea South',
    KOSOVO = 'Kosovo',
    KUWAIT = 'Kuwait',
    KYRGYZSTAN = 'Kyrgyzstan',
    LAOS = 'Laos',
    LATVIA = 'Latvia',
    LEBANON = 'Lebanon',
    LESOTHO = 'Lesotho',
    LIBERIA = 'Liberia',
    LIBYA = 'Libya',
    LIECHTENSTEIN = 'Liechtenstein',
    LITHUANIA = 'Lithuania',
    LUXEMBOURG = 'Luxembourg',
    MACEDONIA = 'Macedonia',
    MADAGASCAR = 'Madagascar',
    MALAWI = 'Malawi',
    MALAYSIA = 'Malaysia',
    MALDIVES = 'Maldives',
    MALI = 'Mali',
    MALTA = 'Malta',
    MARSHALL_ISLANDS = 'Marshall Islands',
    MAURITANIA = 'Mauritania',
    MAURITIUS = 'Mauritius',
    MEXICO = 'Mexico',
    MICRONESIA = 'Micronesia',
    MOLDOVA = 'Moldova',
    MONACO = 'Monaco',
    MONGOLIA = 'Mongolia',
    MONTENEGRO = 'Montenegro',
    MOROCCO = 'Morocco',
    MOZAMBIQUE = 'Mozambique',
    MYANMAR = 'Myanmar',
    NAMIBIA = 'Namibia',
    NAURU = 'Nauru',
    NEPAL = 'Nepal',
    NETHERLANDS = 'Netherlands',
    NEW_ZEALAND = 'New Zealand',
    NICARAGUA = 'Nicaragua',
    NIGER = 'Niger',
    NIGERIA = 'Nigeria',
    NORWAY = 'Norway',
    OMAN = 'Oman',
    PAKISTAN = 'Pakistan',
    PALAU = 'Palau',
    PANAMA = 'Panama',
    PAPUA_NEW_GUINEA = 'Papua New Guinea',
    PARAGUAY = 'Paraguay',
    PERU = 'Peru',
    PHILIPPINES = 'Philippines',
    POLAND = 'Poland',
    PORTUGAL = 'Portugal',
    QATAR = 'Qatar',
    ROMANIA = 'Romania',
    RUSSIAN_FEDERATION = 'Russian Federation',
    RWANDA = 'Rwanda',
    ST_LUCIA = 'St Lucia',
    SAINT_VINCENT = 'Saint Vincent',
    SAMOA = 'Samoa',
    SAN_MARINO = 'San Marino',
    SAO_TOME_AND_PRINCIPE = 'Sao Tome & Principe',
    SAUDI_ARABIA = 'Saudi Arabia',
    SENEGAL = 'Senegal',
    SERBIA = 'Serbia',
    SEYCHELLES = 'Seychelles',
    SIERRA_LEONE = 'Sierra Leone',
    SINGAPORE = 'Singapore',
    SLOVAKIA = 'Slovakia',
    SLOVENIA = 'Slovenia',
    SOLOMON_ISLANDS = 'Solomon Islands',
    SOMALIA = 'Somalia',
    SOUTH_AFRICA = 'South Africa',
    SOUTH_SUDAN = 'South Sudan',
    SPAIN = 'Spain',
    SRI_LANKA = 'Sri Lanka',
    SUDAN = 'Sudan',
    SURINAME = 'Suriname',
    SWAZILAND = 'Swaziland',
    SWEDEN = 'Sweden',
    SWITZERLAND = 'Switzerland',
    SYRIA = 'Syria',
    TAIWAN = 'Taiwan',
    TAJIKISTAN = 'Tajikistan',
    TANZANIA = 'Tanzania',
    THAILAND = 'Thailand',
    TOGO = 'Togo',
    TONGA = 'Tonga',
    TRINIDAD_AND_TOBAGO = 'Trinidad & Tobago',
    TUNISIA = 'Tunisia',
    TURKEY = 'Turkey',
    TURKMENISTAN = 'Turkmenistan',
    TUVALU = 'Tuvalu',
    UGANDA = 'Uganda',
    UKRAINE = 'Ukraine',
    UNITED_ARAB_EMIRATES = 'United Arab Emirates',
    UNITED_KINGDOM = 'United Kingdom',
    UNITED_STATES = 'United States',
    URUGUAY = 'Uruguay',
    UZBEKISTAN = 'Uzbekistan',
    VANUATU = 'Vanuatu',
    VATICAN_CITY = 'Vatican City',
    VENEZUELA = 'Venezuela',
    VIETNAM = 'Vietnam',
    YEMEN = 'Yemen',
    ZAMBIA = 'Zambia',
    ZIMBABWE = 'Zimbabwe',
}

export enum Emotion {
    AFFECTIONATE = 'affectionate',
    AGITATED = 'agitated',
    AMUSED = 'amused',
    ANGRY = 'angry',
    ANNOYED = 'annoyed',
    ANXIOUS = 'anxious',
    ASTONISHED = 'astonished',
    ASTOUNDED = 'astounded',
    CARING = 'caring',
    COMFORTED = 'comforted',
    COMPASSIONATE = 'compassionate',
    CONFIDENT = 'confident',
    CONFUSED = 'confused',
    CONTENT = 'content',
    DELIGHTED = 'delighted',
    DEPRESSED = 'depressed',
    DESPAIRING = 'despairing',
    DEVOTED = 'devoted',
    DISGUSTED = 'disgusted',
    DUMBFOUNDED = 'dumbfounded',
    ELATED = 'elated',
    EMPATHETIC = 'empathetic',
    ENAMORED = 'enamored',
    ENRAGED = 'enraged',
    EXCITED = 'excited',
    FEARFUL = 'fearful',
    FURIOUS = 'furious',
    GRATEFUL = 'grateful',
    GRINNING = 'grinning',
    GLOOMY = 'gloomy',
    HAPPY = 'happy',
    HEARTBROKEN = 'heartbroken',
    HOPELESS = 'hopeless',
    INDIGNANT = 'indignant',
    IRRITATED = 'irritated',
    ISOLATED = 'isolated',
    JOYFUL = 'joyful',
    LONELY = 'lonely',
    LOST = 'lost',
    LOVED = 'loved',
    MELANCHOLIC = 'melancholic',
    MISERABLE = 'miserable',
    MOTIVATED = 'motivated',
    NAUSEATED = 'nauseated',
    NERVOUS = 'nervous',
    OFFENDED = 'offended',
    PANICKED = 'panicked',
    PASSIONATE = 'passionate',
    PERPLEXED = 'perplexed',
    PLEASED = 'pleased',
    REJECTED = 'rejected',
    RELIEVED = 'relieved',
    REPULSED = 'repulsed',
    RESENTFUL = 'resentful',
    SAD = 'sad',
    SCARED = 'scared',
    SERIOUS = 'serious',
    SHOCKED = 'shocked',
    SPEECHLESS = 'speechless',
    STRESSED = 'stressed',
    SURPRISED = 'surprised',
    SYMPATHETIC = 'sympathetic',
    TENDER = 'tender',
    TERRIFIED = 'terrified',
    TENSE = 'tense',
    WARM = 'warm',
    WORRIED = 'worried'
}

export enum Expression {
    AMAZED = 'amazed',
    AMUSED = 'amused',
    ANGRY = 'angry',
    ASTONISHED = 'astonished',
    AWE_STRUCK = 'awe-struck',
    APPALLED = 'appalled',
    BEWILDERED = 'bewildered',
    BORED = 'bored',
    CALM = 'calm',
    CHEERFUL = 'cheerful',
    CONFUSED = 'confused',
    CONTENT = 'content',
    CURIOUS = 'curious',
    DEJECTED = 'dejected',
    DELIGHTED = 'delighted',
    DISTRAUGHT = 'distraught',
    DROWSY = 'drowsy',
    DUMBFOUNDED = 'dumbfounded',
    ECSTATIC = 'ecstatic',
    ELATED = 'elated',
    EXHAUSTED = 'exhausted',
    FRUSTRATED = 'frustrated',
    FURIOUS = 'furious',
    GLOOMY = 'gloomy',
    GRINNING = 'grinning',
    HAPPY = 'happy',
    HEARTBROKEN = 'heartbroken',
    IMPRESSED = 'impressed',
    INDIGNANT = 'indignant',
    INTERESTED = 'interested',
    INTRIGUED = 'intrigued',
    IRRITATED = 'irritated',
    JOVIAL = 'jovial',
    LAUGHING = 'laughing',
    MERRY = 'merry',
    MISERABLE = 'miserable',
    NAUSEATED = 'nauseated',
    OFFENDED = 'offended',
    PEACEFUL = 'peaceful',
    PERPLEXED = 'perplexed',
    PLEASED = 'pleased',
    RADIANT = 'radiant',
    RELAXED = 'relaxed',
    REPULSED = 'repulsed',
    RESENTFUL = 'resentful',
    SAD = 'sad',
    SERENE = 'serene',
    SHOCKED = 'shocked',
    SLEEPY = 'sleepy',
    SMILING = 'smiling',
    SORROWFUL = 'sorrowful',
    SPEECHLESS = 'speechless',
    SURPRISED = 'surprised',
    THRILLED = 'thrilled',
    TIRED = 'tired',
    UNHAPPY = 'unhappy',
    UPSET = 'upset',
    WEARY = 'weary',
    CRY = 'cry',
    DISGUSTED = 'disgusted',
    FEARFUL = 'fearful',
    PATHETIC = 'pathetic',
    SUSPICIOUS = 'suspicious'
}

export enum Eyes {
    ADORABLE = 'adorable',
    ALLURING = 'alluring',
    AMUSING = 'amusing',
    ANIMATED = 'animated',
    ASTUTE = 'astute',
    ATTRACTIVE = 'attractive',
    BEAUTIFUL = 'beautiful',
    BLISSFUL = 'blissful',
    BRILLIANT = 'brilliant',
    CAPTIVATING = 'captivating',
    CELESTIAL = 'celestial',
    CHARISMATIC = 'charismatic',
    CHARMING = 'charming',
    CHEERFUL = 'cheerful',
    CLEVER = 'clever',
    CLOSED = 'closed',
    COMPASSIONATE = 'compassionate',
    CONFIDENT = 'confident',
    CONSTRUCTIVE = 'constructive',
    CREATIVE = 'creative',
    CUTE = 'cute',
    CURIOUS = 'curious',
    DELIGHTFUL = 'delightful',
    DELICATE = 'delicate',
    DIVINE = 'divine',
    DYNAMIC = 'dynamic',
    EFFECTIVE = 'effective',
    ELEGANT = 'elegant',
    ENERGETIC = 'energetic',
    ENCHANTING = 'enchanting',
    ENDEARING = 'endearing',
    ENLIGHTENED = 'enlightened',
    ENTERTAINING = 'entertaining',
    ENTHUSIASTIC = 'enthusiastic',
    ETHEREAL = 'ethereal',
    EXPRESSIVE = 'expressive',
    EXPERT = 'expert',
    FASCINATING = 'fascinating',
    FRIENDLY = 'friendly',
    FUNNY = 'funny',
    GENIUS = 'genius',
    GENUINE = 'genuine',
    GIFTED = 'gifted',
    GLISTENING = 'glistening',
    GORGEOUS = 'gorgeous',
    GRACEFUL = 'graceful',
    HAPPY = 'happy',
    HEAVENLY = 'heavenly',
    HOPEFUL = 'hopeful',
    HONEST = 'honest',
    HYPNOTIC = 'hypnotic',
    IMAGINATIVE = 'imaginative',
    INNOVATIVE = 'innovative',
    INQUISITIVE = 'inquisitive',
    INSIGHTFUL = 'insightful',
    INTELLIGENT = 'intelligent',
    INTENSE = 'intense',
    INVITING = 'inviting',
    JOYFUL = 'joyful',
    KEEN = 'keen',
    KIND = 'kind',
    LIVELY = 'lively',
    LOVELY = 'lovely',
    LOVING = 'loving',
    LUMINOUS = 'luminous',
    MAGICAL = 'magical',
    MASTERFUL = 'masterful',
    MESMERIZING = 'mesmerizing',
    MERRY = 'merry',
    MAGNETIC = 'magnetic',
    MOTIVATING = 'motivating',
    MYSTERIOUS = 'mysterious',
    OBSERVANT = 'observant',
    OPEN = 'open',
    OPTIMISTIC = 'optimistic',
    PASSIONATE = 'passionate',
    PENETRATING = 'penetrating',
    PERCEPTIVE = 'perceptive',
    PLAYFUL = 'playful',
    POSITIVE = 'positive',
    PRODUCTIVE = 'productive',
    PROFICIENT = 'proficient',
    QUICK_WITTED = 'quick-witted',
    RADIANT = 'radiant',
    REFINED = 'refined',
    SEDUCTIVE = 'seductive',
    SHARP = 'sharp',
    SHARP_WITTED = 'sharp-witted',
    SHINING = 'shining',
    SILKY = 'silky',
    SKILLFUL = 'skillful',
    SMART = 'smart',
    SMOOTH = 'smooth',
    SOFT = 'soft',
    SOPHISTICATED = 'sophisticated',
    SOULFUL = 'soulful',
    SPARKLING = 'sparkling',
    SPIRITUAL = 'spiritual',
    STUNNING = 'stunning',
    SUBTLE = 'subtle',
    SUCCESSFUL = 'successful',
    SUPPORTIVE = 'supportive',
    SYMPATHETIC = 'sympathetic',
    TALENTED = 'talented',
    TENDER = 'tender',
    TRANSCENDENT = 'transcendent',
    TRANSLUCENT = 'translucent',
    TRUSTWORTHY = 'trustworthy',
    UPLIFTING = 'uplifting',
    VELVETY = 'velvety',
    VIBRANT = 'vibrant',
    VISIONARY = 'visionary',
    WARM = 'warm',
    WELCOMING = 'welcoming',
    WISE = 'wise',
    WITTY = 'witty',
    WONDERFUL = 'wonderful',
    WINK_LEFT = 'wink_left',
    WINK_RIGHT = 'wink_right'
}

export enum EyesColor {
    BLUE = 'blue',
    LIGHT_BLUE = 'light-blue',
    BLUE_GRAY = 'blue-gray',
    BROWN = 'brown',
    GREEN = 'green',
    HAZEL = 'hazel',
    GRAY = 'gray',
    AMBER = 'amber',
    BLACK = 'black'
}

export enum EyesShape {
    ALMOND_SHAPED = 'almond-shaped',
    ROUND = 'round',
    HOODED = 'hooded',
    UPTURNED = 'upturned',
    DOWNTURNED = 'downturned',
    MONOLID = 'monolid',
    DEEP_SET = 'deep-set',
    WIDE_SET = 'wide-set',
    CLOSE_SET = 'close-set',
    PROTRUDING = 'protruding'
}

export enum Eyelashes {
    LONG = 'long',
    SHORT = 'short',
    CURLY = 'curly',
    STRAIGHT = 'straight',
    DENSE = 'dense',
    SPARSE = 'sparse',
    SHINY = 'shiny',
    MATTE = 'matte',
    BLACK = 'black',
    BROWN = 'brown',
    BLONDE = 'blonde',
    ROUGH = 'rough',
    DAMAGED = 'damaged'
}

export enum Eyebrows {
    ARCHED = 'arched',
    LOW = 'low',
    THICK = 'thick',
    THIN = 'thin',
    LONG = 'long',
    SHORT = 'short',
    STRAIGHT = 'straight',
    CURVED = 'curved',
    DENSE = 'dense',
    SPARSE = 'sparse'
}

export enum Face {
    ASYMMETRICAL = 'asymmetrical',
    BALANCED = 'balanced',
    BULBOUS = 'bulbous',
    DIAMOND_SHAPED = 'diamond-shaped',
    DISPROPORTIONATE = 'disproportionate',
    GRACEFUL = 'graceful',
    HEART_SHAPED = 'heart-shaped',
    OVAL = 'oval',
    RECTANGULAR = 'rectangular',
    ROUND = 'round',
    SQUARE = 'square',
    SYMMETRICAL = 'symmetrical'
}

export enum FacialHair {
    BEARD = 'beard',
    MUSTACHE = 'mustache',
    NONE = 'none'
}

export enum Gaze {
    LEFT = 'left',
    LEFT_UP = 'left-up',
    LEFT_DOWN = 'left-down',
    RIGHT = 'right',
    RIGHT_UP = 'right-up',
    RIGHT_DOWN = 'right-down',
    STRAIGHT = 'straight',
    STRAIGHT_UP = 'straight-up',
    STRAIGHT_DOWN = 'straight-down'
}

export enum Gender {
    FEMALE = 'female',
    MALE = 'male',
    NONE = 'none'
}

export enum Glasses {
    EYEGLASSES = 'eyeglasses',
    SUNGLASSES = 'sunglasses'
}

export enum LightPosition {
    BEHIND = 'behind',
    FRONTAL = 'frontal',
    LEFT = 'left',
    RIGHT = 'right',
    TOP = 'top',
    BOTTOM = 'bottom'
}

export enum Light {
    SOFT = 'soft',
    DYNAMIC = 'dynamic',
    WHITE = 'white',
    BLUE = 'blue',
    RED = 'red',
    GREEN = 'green',
    NEON = 'neon',
    DRAMATIC = 'dramatic',
    STUDIO = 'studio',
    CITY = 'city',
    WARM = 'warm',
    DARK = 'dark',
    NATURAL = 'natural',
    VIVID = 'vivid'
}

export enum Lips {
    BOW_SHAPED = 'bow-shaped',
    CUPIDS_BOW = 'cupid\'s bow',
    DOWNTURNED = 'downturned',
    FULL = 'full',
    FULLER_UPPER = 'fuller upper',
    FULLER_LOWER = 'fuller lower',
    THIN = 'thin',
    PLUMP = 'plump',
    WIDE = 'wide',
    NARROW = 'narrow',
    STRAIGHT = 'straight',
    ROUNDED = 'rounded',
    HEART_SHAPED = 'heart-shaped',
    TAPERED = 'tapered'
}

export enum Hair {
    BUN = 'bun',
    BALD = 'bald',
    COARSE = 'coarse',
    DATED = 'dated',
    DULL = 'dull',
    ELEGANT = 'elegant',
    FINE = 'fine',
    FLAT = 'flat',
    FLOWING = 'flowing',
    FRIZZY = 'frizzy',
    GREASY = 'greasy',
    KEMPT = 'kempt',
    MESSY = 'messy',
    POLISHED = 'polished',
    SILKY = 'silky',
    SLEEK = 'sleek',
    SOPHISTICATED = 'sophisticated',
    SPARSE = 'sparse',
    STRAGGLY = 'straggly',
    STRINGY = 'stringy',
    TEXTURED = 'textured',
    THICK = 'thick',
    TRENDY = 'trendy',
    UNKEMPT = 'unkempt',
    UNRULY = 'unruly',
    VOLUMINOUS = 'voluminous',
    YOUTHFUL = 'youthful'
}

export enum HairType {
    CURLY = 'curly',
    COILY = 'coily',
    KINKY = 'kinky',
    STRAIGHT = 'straight',
    WAVY = 'wavy'
}

export enum HairColor {
    ASHY = 'ashy',
    AUBURN = 'auburn',
    BLACK = 'black',
    BLONDE = 'blonde',
    CARAMEL = 'caramel',
    CHESTNUT = 'chestnut',
    COPPER = 'copper',
    GRAY = 'gray',
    GOLDEN = 'golden',
    PLATINUM = 'platinum',
    RED = 'red',
    STRAWBERRY = 'strawberry',
    WHITE = 'white'
}

export enum HairLength {
    SHORT = 'short',
    MEDIUM = 'medium',
    LONG = 'long',
    PIXIE = 'pixie',
    BOB = 'bob'
}

export enum Makeup {
    FLAWLESS = 'flawless',
    NATURAL = 'natural',
    MATTE = 'matte',
    TANTALIZING = 'tantalizing',
    PORCELAIN = 'porcelain',
    RADIANT = 'radiant',
    WARM = 'warm',
    COOL = 'cool',
    SPARKLING = 'sparkling',
    VIVID = 'vivid'
}

export enum Mouth {
    ARGUING = 'arguing',
    BABBLING = 'babbling',
    BEAMING = 'beaming',
    BICKERING = 'bickering',
    BITING = 'biting',
    BREATHING = 'breathing',
    BROWSING = 'browsing',
    CALM = 'calm',
    CARING = 'caring',
    CHATTING = 'chatting',
    CHEWING = 'chewing',
    CHUCKLING = 'chuckling',
    CLOSED = 'closed',
    CONFUSED = 'confused',
    CONTENT = 'content',
    CRYING = 'crying',
    DEBATING = 'debating',
    DISCUSSING = 'discussing',
    DISTRESSED = 'distressed',
    DROWSY = 'drowsy',
    EXHAUSTED = 'exhausted',
    FROWNING = 'frowning',
    GASPING = 'gasping',
    GARGLING = 'gargling',
    GIGGLING = 'giggling',
    GNAWING = 'gnawing',
    GOSSIPING = 'gossiping',
    GRINNING = 'grinning',
    GRIMACING = 'grimacing',
    GROANING = 'groaning',
    HISSING = 'hissing',
    HALF_OPEN = 'half-open',
    INTRIGUED = 'intrigued',
    JABBERING = 'jabbering',
    LAUGHING = 'laughing',
    LICKING = 'licking',
    LISPING = 'lisping',
    LIPS_POINTED = 'lips-pointed',
    MOUTHING = 'mouthing',
    MOANING = 'moaning',
    MUNCHING = 'munching',
    MUMBLING = 'mumbling',
    NIBBLING = 'nibbling',
    OPEN = 'open',
    POUTING = 'pouting',
    PRATTLING = 'prattling',
    RELAXED = 'relaxed',
    SCREAMING = 'screaming',
    SERENE = 'serene',
    SHOUTING = 'shouting',
    SIGHING = 'sighing',
    SINGING = 'singing',
    SLEEPY = 'sleepy',
    SLURRING = 'slurring',
    SMILING = 'smiling',
    SMIRKING = 'smirking',
    SLOBBERING = 'slobbering',
    STAMMERING = 'stammering',
    STRESSED = 'stressed',
    STUTTERING = 'stuttering',
    SUCKING = 'sucking',
    SURPRISED = 'surprised',
    TALKING = 'talking',
    TENSE = 'tense',
    TIRED = 'tired',
    WEARY = 'weary',
    WHIMPERING = 'whimpering',
    WHISPERING = 'whispering',
    WHISTLING = 'whistling'
}

export enum Nose {
    BIG = 'big',
    BUMPY = 'bumpy',
    BUTTON = 'button',
    CROOKED = 'crooked',
    CUTE = 'cute',
    DELICATE = 'delicate',
    ELEGANT = 'elegant',
    GRACEFUL = 'graceful',
    HOOKED = 'hooked',
    LARGE = 'large',
    LONG = 'long',
    PERFECT = 'perfect',
    PETITE = 'petite',
    PROMINENT = 'prominent',
    REFINED = 'refined',
    SHAPELY = 'shapely',
    STRAIGHT = 'straight',
    WIDE = 'wide'
}

export enum Region {
    NORTH_AMERICA = 'North America',
    SOUTH_AMERICA = 'South America',
    CENTRAL_AMERICA = 'Central America',
    EAST_AMERICA = 'East America',
    WEST_AMERICA = 'West America',
    NORTH_ASIA = 'North Asia',
    SOUTH_ASIA = 'South Asia',
    CENTRAL_ASIA = 'Central Asia',
    EAST_ASIA = 'East Asia',
    WEST_ASIA = 'West Asia',
    NORTH_EUROPE = 'North Europe',
    SOUTH_EUROPE = 'South Europe',
    CENTRAL_EUROPE = 'Central Europe',
    EAST_EUROPE = 'East Europe',
    WEST_EUROPE = 'West Europe',
    NORTH_AFRICA = 'North Africa',
    SOUTH_AFRICA = 'South Africa',
    CENTRAL_AFRICA = 'Central Africa',
    EAST_AFRICA = 'East Africa',
    WEST_AFRICA = 'West Africa',
    MIDDLE_EAST = 'Middle East',
    AUSTRALIA = 'Australia',
    OCEANIA = 'Oceania',
    CARIBBEAN = 'Caribbean'
}

export enum Skin {
    CLEAR = 'clear',
    DARK = 'dark',
    DULL = 'dull',
    DEHYDRATED = 'dehydrated',
    FAIR = 'fair',
    FLUSHED = 'flushed',
    FLAWLESS = 'flawless',
    FRECKLED = 'freckled',
    FLOWING = 'flowing',
    HYDRATED = 'hydrated',
    LIGHT = 'light',
    MATTE = 'matte',
    NATURAL = 'natural',
    OILY = 'oily',
    PALE = 'pale',
    PALE_WHITE = 'pale-white',
    RADIANT = 'radiant',
    ROUGH = 'rough',
    SILKY = 'silky',
    SMOOTH = 'smooth',
    SOFT = 'soft',
    SPOTTY = 'spotty',
    SUPPLE = 'supple',
    SWEATY = 'sweaty',
    WRINKLED = 'wrinkled',
    TANNED = 'tanned',
    TAUT = 'taut'
}

export enum Smile {
    BRIGHT = 'bright',
    RADIANT = 'radiant',
    INFECTIOUS = 'infectious',
    JOYFUL = 'joyful',
    BEAMING = 'beaming',
    CHEERY = 'cheery',
    BLISSFUL = 'blissful',
    ENCHANTING = 'enchanting',
    CAPTIVATING = 'captivating',
    CHARMING = 'charming',
    DELIGHTFUL = 'delightful',
    ENTHRALLING = 'enthralling',
    EXQUISITE = 'exquisite',
    FETCHING = 'fetching',
    GORGEOUS = 'gorgeous',
    HEAVENLY = 'heavenly',
    LOVELY = 'lovely',
    MAGICAL = 'magical',
    MESMERIZING = 'mesmerizing',
    PRETTY = 'pretty',
    RAVISHING = 'ravishing',
    SPLENDID = 'splendid',
    STUNNING = 'stunning',
    SUBLIME = 'sublime',
    SUPERB = 'superb',
    SWEET = 'sweet',
    WONDERFUL = 'wonderful',
    ADORABLE = 'adorable',
    ATTRACTIVE = 'attractive',
    BEAUTIFUL = 'beautiful',
    BEWITCHING = 'bewitching',
    CUTE = 'cute',
    DIVINE = 'divine',
    ELEGANT = 'elegant',
    FASCINATING = 'fascinating',
    GRACEFUL = 'graceful',
    IRRESISTIBLE = 'irresistible',
    MARVELOUS = 'marvelous',
    SEDUCTIVE = 'seductive',
    SENSATIONAL = 'sensational',
    SENSUAL = 'sensual',
    TANTALIZING = 'tantalizing',
    TENDER = 'tender',
    VIBRANT = 'vibrant',
    ALLURING = 'alluring',
    AMIABLE = 'amiable',
    BEGUILING = 'beguiling',
    COMFORTING = 'comforting',
    ENDEARING = 'endearing',
    HEARTWARMING = 'heartwarming',
    LIKEABLE = 'likeable',
    MAGNETIC = 'magnetic',
    PERSONABLE = 'personable',
    WINNING = 'winning'
}

export enum Teeth {
    ALIGNED = 'aligned',
    BEAMING = 'beaming',
    BLINDING = 'blinding',
    BRACED = 'braced',
    BRIGHT = 'bright',
    BROKEN = 'broken',
    CHEWY = 'chewy',
    CHIPPED = 'chipped',
    CLEAN = 'clean',
    CLEAR = 'clear',
    CRUNCHY = 'crunchy',
    CRYSTALLINE = 'crystalline',
    CROOKED = 'crooked',
    CROWNED = 'crowned',
    DAZZLING = 'dazzling',
    DECAYED = 'decayed',
    DISCOLORED = 'discolored',
    ELASTIC = 'elastic',
    FIXED = 'fixed',
    FLAWLESS = 'flawless',
    GAPPED = 'gapped',
    GLEAMING = 'gleaming',
    GLASSY = 'glassy',
    IMMACULATE = 'immaculate',
    IVORY = 'ivory',
    JUICY = 'juicy',
    LUMINOUS = 'luminous',
    LUSTROUS = 'lustrous',
    LUCID = 'lucid',
    MISALIGNED = 'misaligned',
    MISSING = 'missing',
    ORTHODONTIC = 'orthodontic',
    PEARLESCENT = 'pearlescent',
    PERFECT = 'perfect',
    PLUMP = 'plump',
    POLISHED = 'polished',
    RADIANT = 'radiant',
    RESPLENDENT = 'resplendent',
    RUBBERY = 'rubbery',
    SATINY = 'satiny',
    SHIMMERING = 'shimmering',
    SHINY = 'shiny',
    SHEER = 'sheer',
    SILKY = 'silky',
    SLEEK = 'sleek',
    SMILE = 'smile',
    SMOOTH = 'smooth',
    SOFT = 'soft',
    SPONGY = 'spongy',
    SPOTLESS = 'spotless',
    SPARKLING = 'sparkling',
    STAINED = 'stained',
    STRAIGHT = 'straight',
    SUPPLE = 'supple',
    TENDER = 'tender',
    TRANSLUCENT = 'translucent',
    VELVETY = 'velvety',
    WHITE = 'white',
    YELLOWED = 'yellowed'
}

export interface FaceData {
    Age?: number;
    Country?: Country;
    Emotion?: Emotion;
    Expression?: Expression;
    Eyes?: Eyes;
    EyesColor?: EyesColor;
    EyesShape?: EyesShape;
    Eyelashes?: Eyelashes;
    Eyebrows?: Eyebrows;
    Face?: Face;
    FacialHair?: FacialHair;
    Gaze?: Gaze;
    Gender?: Gender;
    Glasses?: Glasses;
    LightPosition?: LightPosition;
    Light?: Light;
    Lips?: Lips;
    Hair?: Hair;
    HairType?: HairType;
    HairColor?: HairColor;
    HairLength?: HairLength;
    Makeup?: Makeup;
    Mouth?: Mouth;
    Nose?: Nose;
    Region?: Region;
    Skin?: Skin;
    Smile?: Smile;
    Teeth?: Teeth;
}
