//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:39 CEST 
//


package com.gentics.contentnode.dbcopy.jaxb;


/**
 * Java content class for PropertiesType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/copy_configuration.xsd line 110)
 * <p>
 * <pre>
 * &lt;complexType name="PropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="property" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JAXBPropertiesType {


    /**
     * 
     * @return
     *     array of
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType[] getPropertyList();

    /**
     * 
     * @return
     *     one of
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType getPropertyList(int idx);

    int getPropertyListLength();

    /**
     * 
     * @param values
     *     allowed objects are
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType}
     */
    void setPropertyList(com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType[] values);

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType setPropertyList(int idx, com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType value);

    boolean isSetPropertyList();

    void unsetPropertyList();


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/copy_configuration.xsd line 118)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface PropertyType {


        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getValue();

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setValue(java.lang.String value);

        boolean isSetValue();

        void unsetValue();

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getId();

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setId(java.lang.String value);

        boolean isSetId();

        void unsetId();

    }

}
