//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:39 CEST 
//


package com.gentics.contentnode.dbcopy.jaxb;


/**
 * Java content class for modificatorsType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/copy_configuration.xsd line 65)
 * <p>
 * <pre>
 * &lt;complexType name="modificatorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modificator" type="{http://www.w3.org/2001/XMLSchema}token" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JAXBmodificatorsType {


    /**
     * 
     * @return
     *     array of
     *     {@link java.lang.String}
     */
    java.lang.String[] getModificator();

    /**
     * 
     * @return
     *     one of
     *     {@link java.lang.String}
     */
    java.lang.String getModificator(int idx);

    int getModificatorLength();

    /**
     * 
     * @param values
     *     allowed objects are
     *     {@link java.lang.String}
     */
    void setModificator(java.lang.String[] values);

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    java.lang.String setModificator(int idx, java.lang.String value);

    boolean isSetModificator();

    void unsetModificator();

}
