//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:39 CEST 
//


package com.gentics.contentnode.dbcopy.jaxb;


/**
 * Java content class for referenceType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/copy_configuration.xsd line 78)
 * <p>
 * <pre>
 * &lt;complexType name="referenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parameter" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="col" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="deepcopy" type="{}deepcopytype" default="true" />
 *       &lt;attribute name="foreigndeepcopy" type="{}deepcopytype" default="true" />
 *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}token" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JAXBreferenceType {


    /**
     * Gets the value of the col property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCol();

    /**
     * Sets the value of the col property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCol(java.lang.String value);

    boolean isSetCol();

    void unsetCol();

    /**
     * Gets the value of the foreigndeepcopy property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getForeigndeepcopy();

    /**
     * Sets the value of the foreigndeepcopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setForeigndeepcopy(java.lang.String value);

    boolean isSetForeigndeepcopy();

    void unsetForeigndeepcopy();

    /**
     * Gets the value of the deepcopy property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDeepcopy();

    /**
     * Sets the value of the deepcopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDeepcopy(java.lang.String value);

    boolean isSetDeepcopy();

    void unsetDeepcopy();

    /**
     * Gets the value of the implementationClass property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getImplementationClass();

    /**
     * Sets the value of the implementationClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setImplementationClass(java.lang.String value);

    boolean isSetImplementationClass();

    void unsetImplementationClass();

    /**
     * 
     * @return
     *     array of
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType[] getParameter();

    /**
     * 
     * @return
     *     one of
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType getParameter(int idx);

    int getParameterLength();

    /**
     * 
     * @param values
     *     allowed objects are
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType}
     */
    void setParameter(com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType[] values);

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType setParameter(int idx, com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType value);

    boolean isSetParameter();

    void unsetParameter();

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTarget();

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTarget(java.lang.String value);

    boolean isSetTarget();

    void unsetTarget();


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/copy_configuration.xsd line 86)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ParameterType {


        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getValue();

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setValue(java.lang.String value);

        boolean isSetValue();

        void unsetValue();

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getId();

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setId(java.lang.String value);

        boolean isSetId();

        void unsetId();

    }

}
