//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:39 CEST 
//


package com.gentics.contentnode.dbcopy.jaxb;


/**
 * Java content class for tableType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/copy_configuration.xsd line 37)
 * <p>
 * <pre>
 * &lt;complexType name="tableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="restrict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modificators" type="{}modificatorsType" minOccurs="0"/>
 *         &lt;element name="references" type="{}referencesType" minOccurs="0"/>
 *         &lt;element name="properties" type="{}PropertiesType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="exportable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="idcol" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="type" default="normal">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="normal"/>
 *             &lt;enumeration value="cross"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface JAXBtableType {


    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setType(java.lang.String value);

    boolean isSetType();

    void unsetType();

    /**
     * Gets the value of the idcol property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getIdcol();

    /**
     * Sets the value of the idcol property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setIdcol(java.lang.String value);

    boolean isSetIdcol();

    void unsetIdcol();

    /**
     * Gets the value of the restrict property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRestrict();

    /**
     * Sets the value of the restrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRestrict(java.lang.String value);

    boolean isSetRestrict();

    void unsetRestrict();

    /**
     * Gets the value of the modificators property.
     * 
     * @return
     *     possible object is
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBmodificatorsType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBmodificatorsType getModificators();

    /**
     * Sets the value of the modificators property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBmodificatorsType}
     */
    void setModificators(com.gentics.contentnode.dbcopy.jaxb.JAXBmodificatorsType value);

    boolean isSetModificators();

    void unsetModificators();

    /**
     * Gets the value of the exportable property.
     * 
     */
    boolean isExportable();

    /**
     * Sets the value of the exportable property.
     * 
     */
    void setExportable(boolean value);

    boolean isSetExportable();

    void unsetExportable();

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setName(java.lang.String value);

    boolean isSetName();

    void unsetName();

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBreferencesType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBreferencesType getReferences();

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBreferencesType}
     */
    void setReferences(com.gentics.contentnode.dbcopy.jaxb.JAXBreferencesType value);

    boolean isSetReferences();

    void unsetReferences();

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setId(java.lang.String value);

    boolean isSetId();

    void unsetId();

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType}
     */
    com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType getProperties();

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType}
     */
    void setProperties(com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType value);

    boolean isSetProperties();

    void unsetProperties();

}
