//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:39 CEST 
//


package com.gentics.contentnode.dbcopy.jaxb;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gentics.contentnode.dbcopy.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.gentics.contentnode.dbcopy.jaxb.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.gentics.contentnode.dbcopy.jaxb.impl.runtime.GrammarInfo grammarInfo = new com.gentics.contentnode.dbcopy.jaxb.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (com.gentics.contentnode.dbcopy.jaxb.ObjectFactory.class));
    public final static java.lang.Class version = (com.gentics.contentnode.dbcopy.jaxb.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType.class), "com.gentics.contentnode.dbcopy.jaxb.impl.JAXBPropertiesTypeImpl.PropertyTypeImpl");
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType.class), "com.gentics.contentnode.dbcopy.jaxb.impl.JAXBreferenceTypeImpl.ParameterTypeImpl");
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.JAXBtableType.class), "com.gentics.contentnode.dbcopy.Table");
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.JAXBmodificatorsType.class), "com.gentics.contentnode.dbcopy.jaxb.impl.JAXBmodificatorsTypeImpl");
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.Tables.class), "com.gentics.contentnode.dbcopy.Tables");
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.TablesType.class), "com.gentics.contentnode.dbcopy.jaxb.impl.TablesTypeImpl");
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.class), "com.gentics.contentnode.dbcopy.jaxb.impl.JAXBPropertiesTypeImpl");
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.class), "com.gentics.contentnode.dbcopy.Reference");
        defaultImplementations.put((com.gentics.contentnode.dbcopy.jaxb.JAXBreferencesType.class), "com.gentics.contentnode.dbcopy.jaxb.impl.JAXBreferencesTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "tables"), (com.gentics.contentnode.dbcopy.jaxb.Tables.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gentics.contentnode.dbcopy.jaxb
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of JAXBPropertiesTypePropertyType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType.PropertyType createJAXBPropertiesTypePropertyType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.jaxb.impl.JAXBPropertiesTypeImpl.PropertyTypeImpl();
    }

    /**
     * Create an instance of JAXBreferenceTypeParameterType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType.ParameterType createJAXBreferenceTypeParameterType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.jaxb.impl.JAXBreferenceTypeImpl.ParameterTypeImpl();
    }

    /**
     * Create an instance of JAXBtableType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.JAXBtableType createJAXBtableType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.Table();
    }

    /**
     * Create an instance of JAXBmodificatorsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.JAXBmodificatorsType createJAXBmodificatorsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.jaxb.impl.JAXBmodificatorsTypeImpl();
    }

    /**
     * Create an instance of Tables
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.Tables createTables()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.Tables();
    }

    /**
     * Create an instance of TablesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.TablesType createTablesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.jaxb.impl.TablesTypeImpl();
    }

    /**
     * Create an instance of JAXBPropertiesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.JAXBPropertiesType createJAXBPropertiesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.jaxb.impl.JAXBPropertiesTypeImpl();
    }

    /**
     * Create an instance of JAXBreferenceType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.JAXBreferenceType createJAXBreferenceType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.Reference();
    }

    /**
     * Create an instance of JAXBreferencesType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.contentnode.dbcopy.jaxb.JAXBreferencesType createJAXBreferencesType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.contentnode.dbcopy.jaxb.impl.JAXBreferencesTypeImpl();
    }

}
