/*
 * @author Stefan Hepp
 * @date 20.01.2006
 * @version $Id: ExpressionParserResult.java,v 1.2 2006-02-03 16:12:26 stefan Exp $
 */
package com.gentics.contentnode.parser.expression.parser;

import com.gentics.contentnode.parser.expression.Expression;

/**
 * This contains the results of a parsing run of an expression parser.
 */
public class ExpressionParserResult {
    
	private Expression expression;
	private int pos;

	/**
	 * Constructor to create a new result container with values.
	 * @param expression the expression generated by the parser, or null if no valid expression was found.
	 * @param pos the position of the first unparsed character in the code.
	 */
	public ExpressionParserResult(Expression expression, int pos) {
		this.expression = expression;
		this.pos = pos;
	}

	/**
	 * get the generated expression.
	 * @return the expression, or null if no expression was generated.
	 */
	public Expression getExpression() {
		return expression;
	}

	/**
	 * get the position of the first unparsed character in the code.
	 * @return the position of the first unparsed char in the code.
	 */
	public int getPosition() {
		return pos;
	}
}
