import { SharedModule } from '@admin-ui/shared/shared.module';
import { NgModule } from '@angular/core';
import { RouterModule, provideRouter, withComponentInputBinding } from '@angular/router';
import {
    AssignConstructsToCategoryModalComponent,
    AssignConstructsToNodesModalComponent,
    BooleanPartFillComponent,
    ConstructCategoryEditorComponent,
    ConstructCategoryMasterComponent,
    ConstructCategoryPropertiesComponent,
    ConstructCategorySortModal,
    ConstructCategoryTableComponent,
    ConstructEditorComponent,
    ConstructMasterComponent,
    ConstructModuleMasterComponent,
    ConstructPartFillComponent,
    ConstructPartListComponent,
    ConstructPartPropertiesComponent,
    ConstructPropertiesComponent,
    CopyConstructModalComponent,
    CreateConstructCategoryModalComponent,
    CreateConstructModalComponent,
    CreateConstructPartModalComponent,
    DataSourcePartFillComponent,
    GenericUrlPartFillComponent,
    JsonPartFillComponent,
    ListPartFillComponent,
    NodeUrlPartFillComponent,
    OverviewPartSettingsComponent,
    PagePartFillComponent,
    SelectOptionInputComponent,
    SelectPartFillComponent,
    SelectPartSettingsComponent,
    StringPartFillComponent,
} from './components';
import { ConstructCategoryTableLoaderService } from './providers';
import { CONSTRUCT_ROUTES } from './construct.routes';

@NgModule({
    declarations: [
        AssignConstructsToCategoryModalComponent,
        AssignConstructsToNodesModalComponent,
        BooleanPartFillComponent,
        ConstructCategoryEditorComponent,
        ConstructCategoryMasterComponent,
        ConstructCategoryPropertiesComponent,
        ConstructCategorySortModal,
        ConstructCategoryTableComponent,
        ConstructEditorComponent,
        ConstructMasterComponent,
        ConstructModuleMasterComponent,
        ConstructPartFillComponent,
        ConstructPartListComponent,
        ConstructPartPropertiesComponent,
        ConstructPropertiesComponent,
        CopyConstructModalComponent,
        CreateConstructCategoryModalComponent,
        CreateConstructModalComponent,
        CreateConstructPartModalComponent,
        DataSourcePartFillComponent,
        GenericUrlPartFillComponent,
        JsonPartFillComponent,
        ListPartFillComponent,
        NodeUrlPartFillComponent,
        OverviewPartSettingsComponent,
        PagePartFillComponent,
        SelectOptionInputComponent,
        SelectPartFillComponent,
        SelectPartSettingsComponent,
        StringPartFillComponent,
    ],
    providers: [
        ConstructCategoryTableLoaderService,
        provideRouter(CONSTRUCT_ROUTES, withComponentInputBinding()),
    ],
    imports: [
        SharedModule,
        RouterModule.forChild(CONSTRUCT_ROUTES),
    ],
})
export class ConstructModule { }
