services:
  mariadb:
    extends:
      file: compose.yml
      service: mariadb

  mesh:
    extends:
      file: compose.yml
      service: mesh
    environment:
      LICENSEKEY: "${CI_LICENSEKEY}"

  cms:
    extends:
      file: compose.yml
      service: cms
    image: docker.gentics.com/gentics/cms:${CI_CMS_VERSION:-ci-devtest}

    environment:
      ELASTICSEARCH_ENABLED: "false" # Disabled until ES 8 compat is ready
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      LICENSEKEY: "${CI_LICENSEKEY}"

    volumes:
      - ./cms/ui-conf:/cms/ui-conf

    extra_hosts:
      - "keycloak.localhost.gentics.com:host-gateway"

    depends_on:
      mariadb:
        condition: service_healthy
      mesh:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      web:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev --import-realm
    ports:
      - 8180:8080

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HEALTH_ENABLED: "true"
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mariadb/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

    volumes:
      - ./keycloak:/opt/keycloak/data/import

    depends_on:
      mariadb:
        condition: service_healthy

    healthcheck:
      # Really stupid health check because the keycloak image doesn't contain curl nor wget
      # https://stackoverflow.com/a/78229437
      test: [
        "CMD-SHELL",
        'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
      ]
      start_period: 300s
      # start_interval: 10s
      interval: 60s
      timeout: 10s
      retries: 3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    ports:
      - 9200:9200

    environment:
      # Single instance, i.E. disable clustering
      - discovery.type=single-node
      # Disable swap
      - bootstrap.memory_lock=true
      # Disable SSL, as we don't need it here
      - xpack.security.enabled=false
      # Disable machine learning
      - xpack.ml.enabled=false

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      start_period: 120s
      # start_interval: 10s
      interval: 60s
      timeout: 30s
      retries: 3

  web:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"

    volumes:
      - ./web/conf.d:/etc/nginx/conf.d:ro

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      start_period: 10s
      # start_interval: 5s
      interval: 60s
      timeout: 10s
      retries: 3
