services:
  mariadb:
    extends:
      file: compose.yml
      service: mariadb

  mesh:
    extends:
      file: compose.yml
      service: mesh

  cms:
    extends:
      file: compose.yml
      service: cms

  app:
    build:
      dockerfile: ./cms-integration-tests/local.Dockerfile
      context: ../
    entrypoint: "npm ci --no-fund --no-audit && npm run nx -- run-many --targets=e2e --projects=tag:e2e --configuration=ci --parallel=false --output-style=static --verbose"

    environment:
      CMS_VARIANT: OSS

    network_mode: host

    depends_on:
      cms:
        condition: service_healthy
