../cms-ui/.angular
../cms-ui/.nx
../cms-ui/dist
../cms-ui/node_modules
../cms-ui/target
../cms-ui/tmp

cms-ui/.angular
cms-ui/.nx
cms-ui/dist
cms-ui/node_modules
cms-ui/target
cms-ui/tmp

.angular
.nx
dist
node_modules
target
tmp
