FROM node:20.12.1-slim

# For later installs
ENV PLAYWRIGHT_BROWSERS_PATH=0
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Install debugging tools
RUN apt-get update && \
    apt-get install -y curl wget gpg ca-certificates && \
    # clean apt cache
    rm -rf /var/lib/apt/lists/*

# Create app dir for the tests to be mounted into
RUN mkdir /app
VOLUME /app
WORKDIR /app

# Setup scripts dir
RUN mkdir /scripts
VOLUME /scripts

# Copy initial scripts into the container
COPY ./cms-integration-tests/playwright/* /scripts
RUN chmod +x /scripts/*.sh
RUN chown -R node /scripts

EXPOSE 3000

ENTRYPOINT [ "/scripts/entrypoint.sh"]
