---
title: "Aloha Editor Gentics CMS Plugins"
description: "Explains how to load plugins and add new ones"
---
= Aloha Editor Gentics CMS Plugins

Plugin configuration guide for Aloha Editor >= 0.10 and newer

[#plugin-names]
== Plugin Names

Plugin names have changed to be much more compact, and are now organized in plugin bundles.
Therefore you need to change your Aloha Editor configuration if you're switching from 0.9.3.
Please have a look at the https://github.com/alohaeditor/Aloha-Editor/tree/dev/src/plugins/common[common bundle] and the extra bundle to learn their new names.
Common bundles will be actively maintained and kept up to date with Aloha Editor's core, whilst the https://github.com/alohaeditor/Aloha-Editor/tree/dev/src/plugins/extra[extra bundle] might not always be most up to date.

[#list-of-default-plugins]
== List of default plugins

This is the default list of plugins:

.conf/*.yml
[source,javascript]
----
aloha_plugins_global:
  - "gcn/gcn"
  - "common/ui"
  - "common/block"
  - "common/format"
  - "common/autoparagraph"
  - "common/highlighteditables"
  - "common/list"
  - "common/link"
  - "common/table"
  - "common/paste"
  - "common/contenthandler"
  - "common/commands"
  - "common/dom-to-xhtml"
----

NOTE: The Gentics CMS Integration Plugin "gcn/gcn" will always be added automatically, if not contained in this list.

[#configure-list-of-loaded-plugins]
== Configure list of loaded plugins

With the following setting, the global plugin list can be configured.

.conf/*.yml
[source,javascript]
----
aloha_plugins_global:
  - "common/ui"
  - "common/block"
  - "common/autoparagraph"
  - "common/highlighteditables"
  - "common/list"
  - "common/link"
  - "common/table"
  - "common/paste"
  - "common/contenthandler"
  - "common/commands"
  - "common/dom-to-xhtml"
  - "extra/cite"
----

WARNING: Please note, that by overwriting the setting `+aloha_plugins_global+` plugins array, future updates of Gentics CMS, that introduce new plugins will not automatically take effect.

[#per-node-plugin-list]
== Per Node Plugin List

It is also possible to configure the loaded plugins per node, using either the local ID or global ID or the name of the node. Note that this will override the plugin list defined in `+aloha_plugins_global+`, and can therefore also be used to disable a certain global plugin for a node by specifying a custom plugin list without the plugin to exclude.

NOTE: Configuration per local ID, global ID and name cannot be mixed. The CMS will first look for a configuration by global ID, if that is not found, by node name and if that is not found by local ID.

NOTE: In multichannelling environments, the configuration is only applied to the specified node/channel and not to other channels of the same channel structure.

.conf/*.yml
[source,javascript]
----
# Define the Aloha Editor plugins list for Node with global ID 3D6C.bbcc391e-ae22-11e9-9f0d-00155df0382f
aloha_plugins_node:
  "3D6C.bbcc391e-ae22-11e9-9f0d-00155df0382f":
    - "common/ui"
    - "common/block"
    - "common/autoparagraph"
    - "common/highlighteditables"
    - "common/list"
    - "common/link"
    - "common/table"
    - "common/paste"
    - "common/contenthandler"
    - "common/commands"
    - "common/dom-to-xhtml"
    - "extra/cite"
----
