import { IS_NORMALIZED, NormalizedEntityStore, RecursivePartial } from '../models';
import { getExampleImageDataNormalized, getExampleNodeDataNormalized } from './test-data.mock';

export function getExampleEntityStore(): NormalizedEntityStore {
    const ret: RecursivePartial<NormalizedEntityStore> = {
        file: {
            10: {
                ...getExampleImageDataNormalized({ id: 10, userId: 1 }) as any,
                type: 'file',
                folderId: 4,
                folder: 4,
            },
        },
        folder: {
            1: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/',
                excluded: false,
                name: 'GCN5 Demo',
                creator: 3,
                isMaster: true,
                disinherited: false,
                editor: 3,
                cdate: 1280413310,
                edate: 1295049499,
                disinheritDefault: false,
                channelsetId: 194,
                inherited: false,
                // This is an ugly hack to fool TypeScript for mocking the entities, because the CMS actually returns a node's root folders with type='node'.
                type: 'node' as any,
                id: 1,
                atposidx: '-1',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.69433',
                publishDir: '/',
                channelId: 0,
                hasSubfolders: true,
                subfolders: [ 2, 4 ],
                [IS_NORMALIZED]: true,
            },
            2: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/[Templates]/',
                excluded: false,
                name: '[Templates]',
                creator: 3,
                isMaster: true,
                disinherited: false,
                editor: 3,
                cdate: 1280413327,
                edate: 1286191751,
                disinheritDefault: false,
                channelsetId: 195,
                inherited: false,
                type: 'folder',
                id: 2,
                atposidx: '-1-2',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.69436',
                publishDir: '/templates/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: true,
                [IS_NORMALIZED]: true,
            },
            4: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Home/',
                excluded: false,
                name: 'Home',
                creator: 3,
                isMaster: true,
                disinherited: false,
                startPageId: 1,
                editor: 3,
                cdate: 1280413358,
                edate: 1282122319,
                disinheritDefault: false,
                channelsetId: 197,
                inherited: false,
                type: 'folder',
                id: 4,
                atposidx: '-1-4',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.69444',
                publishDir: '/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: true,
                [IS_NORMALIZED]: true,
            },
            5: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Departments/',
                excluded: false,
                name: 'Departments',
                creator: 3,
                isMaster: true,
                disinherited: false,
                startPageId: 72,
                editor: 3,
                cdate: 1282122335,
                edate: 1282122335,
                disinheritDefault: false,
                channelsetId: 198,
                inherited: false,
                type: 'folder',
                id: 5,
                atposidx: '-1-5',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.69458',
                publishDir: '/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: true,
                [IS_NORMALIZED]: true,
            },
            6: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Projects-Wiki/',
                excluded: false,
                name: 'Projects-Wiki',
                creator: 3,
                isMaster: true,
                disinherited: false,
                startPageId: 48,
                editor: 3,
                cdate: 1282122345,
                edate: 1288364605,
                disinheritDefault: false,
                channelsetId: 199,
                inherited: false,
                type: 'folder',
                id: 6,
                atposidx: '-1-6',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.69462',
                publishDir: '/projects/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: true,
                [IS_NORMALIZED]: true,
            },
            7: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Corporate Blog/',
                excluded: false,
                name: 'Corporate Blog',
                creator: 3,
                isMaster: true,
                disinherited: false,
                startPageId: 3,
                editor: 3,
                cdate: 1282122362,
                edate: 1286191677,
                disinheritDefault: false,
                channelsetId: 200,
                inherited: false,
                type: 'folder',
                id: 7,
                atposidx: '-1-7',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.69466',
                publishDir: '/blog/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: true,
                [IS_NORMALIZED]: true,
            },
            21: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/News/',
                excluded: false,
                name: 'News',
                creator: 3,
                isMaster: true,
                disinherited: false,
                startPageId: 16,
                editor: 3,
                cdate: 1286190158,
                edate: 1286190158,
                disinheritDefault: false,
                channelsetId: 209,
                inherited: false,
                type: 'folder',
                id: 21,
                atposidx: '-1-21',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.70402',
                publishDir: '/news/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: false,
                [IS_NORMALIZED]: true,
            },
            23: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Corporate Blog/Blogposts/',
                excluded: false,
                name: 'Blogposts',
                creator: 3,
                isMaster: true,
                disinherited: false,
                startPageId: 3,
                editor: 3,
                cdate: 1286191666,
                edate: 1288362276,
                disinheritDefault: false,
                channelsetId: 210,
                inherited: false,
                type: 'folder',
                id: 23,
                atposidx: '-1-7-23',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.70907',
                publishDir: '/blog/posts/',
                channelId: 0,
                motherId: 7,
                hasSubfolders: false,
                [IS_NORMALIZED]: true,
            },
            24: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/[Media]/',
                excluded: false,
                name: '[Media]',
                creator: 3,
                isMaster: true,
                disinherited: false,
                editor: 3,
                cdate: 1288364731,
                edate: 1288688181,
                disinheritDefault: false,
                channelsetId: 211,
                inherited: false,
                type: 'folder',
                id: 24,
                atposidx: '-1-24',
                description: '',
                nodeId: 1,
                masterId: 0,
                globalId: 'A547.72004',
                publishDir: '/media/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: true,
                [IS_NORMALIZED]: true,
            },
            56: {
                inheritedFrom: 'test node',
                masterNode: 'test node',
                path: '/test node/',
                excluded: false,
                name: 'test node',
                creator: 3,
                isMaster: true,
                disinherited: false,
                editor: 3,
                cdate: 1462201070,
                edate: 1462201070,
                disinheritDefault: false,
                channelsetId: 234,
                inherited: false,
                type: 'node' as any,
                id: 56,
                atposidx: '-56',
                description: 'test',
                nodeId: 3,
                masterId: 0,
                globalId: 'CD6F.3d677509-1076-11e6-8c26-0242ac120002',
                publishDir: '/',
                channelId: 0,
                hasSubfolders: true,
                [IS_NORMALIZED]: true,
            },
            58: {
                inheritedFrom: 'Channel',
                masterNode: 'GCN5 Demo',
                path: '/Channel/',
                excluded: false,
                name: 'Channel',
                creator: 3,
                isMaster: false,
                disinherited: false,
                editor: 3,
                cdate: 1464606231,
                edate: 1464606231,
                disinheritDefault: false,
                channelsetId: 194,
                inherited: false,
                type: 'channel' as any,
                id: 58,
                atposidx: '-58',
                description: '',
                nodeId: 4,
                masterId: 1,
                globalId: 'CD6F.31162c1b-2656-11e6-a1ee-0242ac120004',
                publishDir: '/',
                channelId: 4,
                hasSubfolders: true,
                [IS_NORMALIZED]: true,
            },
            59: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Test/',
                excluded: false,
                name: 'Test',
                creator: 3,
                isMaster: true,
                disinherited: false,
                editor: 3,
                cdate: 1464609157,
                edate: 1464609157,
                disinheritDefault: false,
                channelsetId: 238,
                inherited: false,
                type: 'folder',
                id: 59,
                atposidx: '-1-59',
                description: 'a test',
                nodeId: 1,
                masterId: 0,
                globalId: 'CD6F.01081eb1-265d-11e6-a1ee-0242ac120004',
                publishDir: '/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: false,
                [IS_NORMALIZED]: true,
            },
            60: {
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Another test/',
                excluded: false,
                name: 'Another test',
                creator: 3,
                isMaster: true,
                disinherited: false,
                editor: 3,
                cdate: 1464609284,
                edate: 1464609284,
                disinheritDefault: false,
                channelsetId: 239,
                inherited: false,
                type: 'folder',
                id: 60,
                atposidx: '-1-60',
                description: 'yet agaun',
                nodeId: 1,
                masterId: 0,
                globalId: 'CD6F.4cabc23e-265d-11e6-a1ee-0242ac120004',
                publishDir: '/',
                channelId: 0,
                motherId: 1,
                hasSubfolders: false,
                [IS_NORMALIZED]: true,
            },
            61: {
                inheritedFrom: 'Channel',
                masterNode: 'Channel',
                path: '/GCN5 Demo/foo/',
                excluded: false,
                name: 'foo',
                creator: 3,
                isMaster: true,
                disinherited: false,
                editor: 3,
                cdate: 1464794829,
                edate: 1464794829,
                disinheritDefault: false,
                channelsetId: 240,
                inherited: false,
                type: 'folder',
                id: 61,
                atposidx: '-1-61',
                description: 'a foo',
                nodeId: 1,
                masterId: 0,
                globalId: 'CD6F.4e92bec7-280d-11e6-b1dc-0242ac120004',
                publishDir: '/',
                channelId: 4,
                motherId: 1,
                hasSubfolders: false,
                [IS_NORMALIZED]: true,
            },
        },
        group: {
            1: {
                id: 1,
                name: 'Power Users',
                description: '',
                children: [ 2 ],
                [IS_NORMALIZED]: true,
            },
            2: {
                id: 2,
                name: 'Administrators',
                description: '',
                [IS_NORMALIZED]: true,
            },
        },
        image: {
            10: {
                ...getExampleImageDataNormalized({ id: 10, userId: 1 }),
                folderId: 4,
                folder: 4,
            },
        },
        language: {
            1: {
                code: 'de',
                name: 'Deutsch (German)',
                id: 1,
            },
            2: {
                code: 'en',
                name: 'English',
                id: 2,
            },
        },
        message: {
            1000: {
                id: 1000,
                message: 'Test Message',
                sender: 1,
                unread: true,
                [IS_NORMALIZED]: true,
            },
        },
        node: {
            1: getExampleNodeDataNormalized({ id: 1, userId: 1}),
        },
        page: {
            3: {
                contentGroupId: 2,
                master: true,
                readOnly: false,
                liveUrl: '',
                languageName: 'English',
                contentSetId: 1525,
                inheritedFrom: 'GCN5 Demo',
                priority: 1,
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Corporate Blog/',
                languageVariants: {
                    1: 37,
                    2: 3,
                },
                pageVariants: [ 37 ],
                fileName: 'Corporate-Blog.en.html',
                folderId: 7,
                folder: 7,
                excluded: false,
                locked: false,
                name: 'Corporate Blog',
                creator: 3,
                disinherited: false,
                editor: 3,
                lockedSince: -1,
                timeManagement: {
                    at: 0,
                    offlineAt: 0,
                },
                cdate: 1282146337,
                edate: 1361283136,
                online: true,
                disinheritDefault: false,
                contentId: 3,
                templateId: 1,
                language: 'en',
                template: 1,
                channelSetId: 2,
                inherited: false,
                type: 'page',
                id: 3,
                publisher: 1,
                description: '',
                globalId: 'A547.69584',
                pdate: 1361283136,
                [IS_NORMALIZED]: true,
            },
            37: {
                contentGroupId: 1,
                master: true,
                readOnly: false,
                liveUrl: '',
                languageName: 'Deutsch (German)',
                contentSetId: 1525,
                inheritedFrom: 'GCN5 Demo',
                priority: 1,
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Corporate Blog/',
                fileName: 'Corporate-Blog.de.html',
                folderId: 7,
                excluded: false,
                locked: false,
                name: 'Corporate Blog',
                creator: 3,
                disinherited: false,
                editor: 3,
                lockedSince: -1,
                timeManagement: {
                    at: 0,
                    offlineAt: 0,
                },
                cdate: 1282146337,
                edate: 1315919150,
                online: true,
                disinheritDefault: false,
                contentId: 37,
                templateId: 1,
                language: 'de',
                template: 1,
                channelSetId: 19,
                inherited: false,
                type: 'page',
                id: 37,
                publisher: 1,
                description: '',
                globalId: 'A547.72111',
                pdate: 1315919153,
                [IS_NORMALIZED]: true,
            },
        },
        template: {
            1: {
                markupLanguage: {
                    contentType: 'text/html',
                    name: 'HTML',
                    id: 1,
                    extension: 'html',
                },
                master: true,
                path: '/GCN5 Demo/Corporate Blog/',
                folderId: 7,
                locked: false,
                name: 'Contentpage',
                creator: 1,
                editor: 1,
                cdate: 1280413392,
                edate: 1316086962,
                channelSetId: 66,
                inherited: false,
                id: 1,
                description: '',
                globalId: 'A547.69449',
                [IS_NORMALIZED]: true,
            },
            2: {
                markupLanguage: {
                    contentType: 'text/html',
                    name: 'HTML',
                    id: 1,
                    extension: 'html',
                },
                master: true,
                inheritedFrom: 'GCN5 Demo',
                masterNode: 'GCN5 Demo',
                path: '/GCN5 Demo/Projects-Wiki/',
                folderId: 79,
                locked: false,
                name: 'Wikipage',
                creator: 1,
                editor: 1,
                cdate: 1282822902,
                edate: 1316086982,
                channelSetId: 68,
                inherited: false,
                id: 4,
                description: '',
                globalId: 'A547.69793',
                [IS_NORMALIZED]: true,
            },
        },
        user: {
            1: {
                email: 'nowhere@gentics.com',
                lastName: 'Gentics',
                firstName: '.Node',
                id: 1,
                [IS_NORMALIZED]: true,
            },
            3: {
                description: 'System Administrator',
                email: 'nowhere@gentics.com',
                login: 'node',
                lastName: 'Admin',
                firstName: 'Node',
                id: 3,
                groups: [ 1, 2 ],
                [IS_NORMALIZED]: true,
            },
        },
    };

    return ret as any;
}
