resourcePackages:
- com.gentics.contentnode.rest.resource
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: ${project.version}
    title: Gentics CMS OSS REST API
    description: OpenAPI specification for Gentics CMS OSS
    contact:
      url: ${project.url}
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html
  components:
    securitySchemes:
      bearerAuth:
        type: http
        description: CMS API Token
        scheme: bearer
      sessionSecret:
        type: apiKey
        description: CMS session secret
        name: GCN_SESSION_SECRET
        in: cookie
  security:
  - bearerAuth: []
  - sessionSecret: []