/* eslint-disable @typescript-eslint/indent */
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { CmsComponentsModule, WindowRef } from '@gentics/cms-components';
import { FormGeneratorModule } from '@gentics/form-generator';
import { GenticsUICoreModule } from '@gentics/ui-core';
import { NgxPaginationModule } from 'ngx-pagination';
import { FolderContextMenuComponent } from '../core/components/folder-context-menu/folder-context-menu.component';
import { WastebinList } from '../core/components/wastebin-list/wastebin-list.component';
import { ReplaceEscapedCharactersPipe } from '../list-view/pipes/replace-escaped-characters/replace-escaped-characters.pipe';
import {
    ChannelDependenciesModal,
    ChipSearchBarComponent,
    DetailChip,
    DisplayFieldSelector,
    ExternalAssetsModalComponent,
    FavouriteToggleComponent,
    FilePropertiesForm,
    FileStatusLabel,
    FolderPropertiesForm,
    FormLanguageIndicatorComponent,
    FormLanguageIndicatorCurrentComponent,
    FormLanguageSelectorComponent,
    FormPropertiesFormComponent,
    IconCheckbox,
    ImageThumbnailComponent,
    ImageThumbnailTooltip,
    InheritanceDialog,
    InheritedLocalizedIcon,
    InputSelectComponent,
    ItemBreadcrumbsComponent,
    ItemContextMenuComponent,
    ItemListRowComponent,
    ItemStateContextMenuComponent,
    ItemStatusLabelComponent,
    LanguageContextSelectorComponent,
    LinkTemplateComponent,
    LinkTemplateModal,
    ListFilterComponent,
    ListItemDetails,
    MasonryGridComponent,
    MultiDeleteModal,
    MultiMoveModal,
    MultiRestoreModalComponent,
    NodeSelectorComponent,
    NodeSelectorTree,
    PageLanguageIndicatorComponent,
    PageLanguageIndicatorCurrentComponent,
    PageLanguageSelector,
    PagePropertiesForm,
    PageSizeSelectorComponent,
    PageVersionsModal,
    PagingControls,
    ProxyRouteComponent,
    PublishPagesModalComponent,
    PublishTimeManagedPagesModal,
    RepositoryBrowser,
    RepositoryBrowserBreadcrumbs,
    RepositoryBrowserList,
    RepositoryBrowserListHeader,
    RepositoryBrowserListItem,
    RepositoryBrowserListThumbnail,
    RessourceProxyComponent,
    SearchSuggestionBarComponent,
    SearchSuggestionComponent,
    MessagePropertiesComponent,
    SendMessageModal,
    SortingModal,
    StartPageIcon,
    SynchronizeChannelModal,
    TakePagesOfflineModal,
    TimeManagementModal,
    TranslatePageModal,
    UploadButtonComponent,
    UsageListComponent,
    UsageModalComponent,
} from './components';
import {
    DynamicDisableDirective,
    MasonryItemDirective,
    OverrideSlotDirective,
} from './directives';
import {
    AllItemsSelectedPipe,
    CapitalizePipe,
    DependenciesCountPipe,
    FileSizePipe,
    GetInheritancePipe,
    HighlightPipe,
    I18nDatePipe,
    I18nPipe,
    ImageDimensionsPipe,
    IsFavouritePipe,
    IsStartPagePipe,
    ItemIsLocalizedPipe,
    ItemIsLocalPipe,
    ItemPathPipe,
    NodeNameOfItemPipe,
    PageIsLockedPipe,
    PermissionsPipe,
    RouterCommandsForItemPipe,
    TruncateNumberPipe,
    TruncatePathPipe,
    TypeIconPipe,
    UserFullNamePipe,
} from './pipes';
import {
    BreadcrumbsService,
    ChipSearchBarConfigService,
    DocumentRef,
    LinkTemplateService,
    PresentationService,
    QueryAssemblerElasticSearchService,
    QueryAssemblerGCMSSearchService,
    RepositoryBrowserClient,
    SuggestionSearchService,
    UIOverridesService,
    UserAgentRef,
    TranslationActionsService,
} from './providers';

const COMPONENTS = [
    ChipSearchBarComponent,
    DetailChip,
    DynamicDisableDirective,
    FavouriteToggleComponent,
    FilePropertiesForm,
    FileStatusLabel,
    FolderContextMenuComponent,
    FolderPropertiesForm,
    FormLanguageIndicatorComponent,
    FormLanguageIndicatorComponent,
    FormLanguageIndicatorCurrentComponent,
    FormLanguageSelectorComponent,
    FormPropertiesFormComponent,
    IconCheckbox,
    ImageThumbnailComponent,
    ImageThumbnailTooltip,
    InheritedLocalizedIcon,
    InputSelectComponent,
    ItemBreadcrumbsComponent,
    ItemContextMenuComponent,
    ItemListRowComponent,
    ItemStateContextMenuComponent,
    ItemStatusLabelComponent,
    LanguageContextSelectorComponent,
    ListFilterComponent,
    ListItemDetails,
    MasonryGridComponent,
    MasonryItemDirective,
    NodeSelectorComponent,
    NodeSelectorTree,
    OverrideSlotDirective,
    PageLanguageIndicatorComponent,
    PageLanguageIndicatorCurrentComponent,
    PageLanguageSelector,
    PagePropertiesForm,
    PageSizeSelectorComponent,
    PagingControls,
    ProxyRouteComponent,
    RepositoryBrowserBreadcrumbs,
    RepositoryBrowserList,
    RepositoryBrowserListHeader,
    RepositoryBrowserListItem,
    RepositoryBrowserListThumbnail,
    RessourceProxyComponent,
    StartPageIcon,
    SearchSuggestionBarComponent,
    SearchSuggestionComponent,
    UploadButtonComponent,
    WastebinList,
];

const ENTRY_COMPONENTS = [
    ChannelDependenciesModal,
    DisplayFieldSelector,
    ExternalAssetsModalComponent,
    InheritanceDialog,
    LinkTemplateComponent,
    LinkTemplateModal,
    MultiDeleteModal,
    MultiMoveModal,
    MultiRestoreModalComponent,
    PageVersionsModal,
    PublishPagesModalComponent,
    PublishTimeManagedPagesModal,
    RepositoryBrowser,
    MessagePropertiesComponent,
    SendMessageModal,
    SortingModal,
    SynchronizeChannelModal,
    TakePagesOfflineModal,
    TimeManagementModal,
    TranslatePageModal,
    UsageListComponent,
    UsageModalComponent,
];

const PIPES = [
    AllItemsSelectedPipe,
    CapitalizePipe,
    DependenciesCountPipe,
    FileSizePipe,
    GetInheritancePipe,
    HighlightPipe,
    I18nDatePipe,
    I18nPipe,
    ImageDimensionsPipe,
    IsFavouritePipe,
    IsStartPagePipe,
    ItemIsLocalizedPipe,
    ItemIsLocalPipe,
    ItemPathPipe,
    NodeNameOfItemPipe,
    PageIsLockedPipe,
    PermissionsPipe,
    ReplaceEscapedCharactersPipe,
    RouterCommandsForItemPipe,
    TruncateNumberPipe,
    TruncatePathPipe,
    TypeIconPipe,
    UserFullNamePipe,
];

const IMPORTS: any[] = [
    CommonModule,
    FormsModule,
    GenticsUICoreModule,
    CmsComponentsModule,
    NgxPaginationModule,
    ReactiveFormsModule,
    RouterModule,
    FormGeneratorModule.forRoot(),
];

const DECLARATIONS = [...COMPONENTS, ...ENTRY_COMPONENTS, ...PIPES];

const PROVIDERS = [
    BreadcrumbsService,
    ChipSearchBarConfigService,
    DocumentRef,
    LinkTemplateService,
    PresentationService,
    QueryAssemblerElasticSearchService,
    QueryAssemblerGCMSSearchService,
    RepositoryBrowserClient,
    SuggestionSearchService,
    UIOverridesService,
    UserAgentRef,
    WindowRef,
    TranslationActionsService,
];

@NgModule({
    imports: [
        IMPORTS,
    ],
    exports: [
        ...DECLARATIONS,
        ...IMPORTS,
    ],
    declarations: DECLARATIONS,
    providers: PROVIDERS,
})
export class SharedModule {}
