//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:30 CEST 
//


package com.gentics.lib.datasource.object.jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/objecttypes.xsd line 14)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objecttype" type="{}objecttype" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface DefinitionType {


    /**
     * 
     * @return
     *     array of
     *     {@link com.gentics.lib.datasource.object.jaxb.Objecttype}
     */
    com.gentics.lib.datasource.object.jaxb.Objecttype[] getObjectTypes();

    /**
     * 
     * @return
     *     one of
     *     {@link com.gentics.lib.datasource.object.jaxb.Objecttype}
     */
    com.gentics.lib.datasource.object.jaxb.Objecttype getObjectTypes(int idx);

    int getObjectTypesLength();

    /**
     * 
     * @param values
     *     allowed objects are
     *     {@link com.gentics.lib.datasource.object.jaxb.Objecttype}
     */
    void setObjectTypes(com.gentics.lib.datasource.object.jaxb.Objecttype[] values);

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.gentics.lib.datasource.object.jaxb.Objecttype}
     */
    com.gentics.lib.datasource.object.jaxb.Objecttype setObjectTypes(int idx, com.gentics.lib.datasource.object.jaxb.Objecttype value);

    boolean isSetObjectTypes();

    void unsetObjectTypes();

}
