//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:30 CEST 
//


package com.gentics.lib.datasource.object.jaxb;


/**
 * Java content class for objecttype complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/johannes2/workspace_cn/node/node-lib/src/main/xsd/objecttypes.xsd line 29)
 * <p>
 * <pre>
 * &lt;complexType name="objecttype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attributetype" type="{}attributetype" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="excludeversioning" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Objecttype {


    /**
     * 
     * @return
     *     array of
     *     {@link com.gentics.lib.datasource.object.jaxb.Attributetype}
     */
    com.gentics.lib.datasource.object.jaxb.Attributetype[] getAttributeTypes();

    /**
     * 
     * @return
     *     one of
     *     {@link com.gentics.lib.datasource.object.jaxb.Attributetype}
     */
    com.gentics.lib.datasource.object.jaxb.Attributetype getAttributeTypes(int idx);

    int getAttributeTypesLength();

    /**
     * 
     * @param values
     *     allowed objects are
     *     {@link com.gentics.lib.datasource.object.jaxb.Attributetype}
     */
    void setAttributeTypes(com.gentics.lib.datasource.object.jaxb.Attributetype[] values);

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.gentics.lib.datasource.object.jaxb.Attributetype}
     */
    com.gentics.lib.datasource.object.jaxb.Attributetype setAttributeTypes(int idx, com.gentics.lib.datasource.object.jaxb.Attributetype value);

    boolean isSetAttributeTypes();

    void unsetAttributeTypes();

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setName(java.lang.String value);

    boolean isSetName();

    void unsetName();

    /**
     * Gets the value of the excludeVersioning property.
     * 
     */
    boolean isExcludeVersioning();

    /**
     * Sets the value of the excludeVersioning property.
     * 
     */
    void setExcludeVersioning(boolean value);

    boolean isSetExcludeVersioning();

    void unsetExcludeVersioning();

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Integer}
     */
    java.lang.Integer getId();

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Integer}
     */
    void setId(java.lang.Integer value);

    boolean isSetId();

    void unsetId();

}
