//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-hudson-16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 01:20:30 CEST 
//


package com.gentics.lib.datasource.object.jaxb;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gentics.lib.datasource.object.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.gentics.lib.datasource.object.jaxb.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.gentics.lib.datasource.object.jaxb.impl.runtime.GrammarInfo grammarInfo = new com.gentics.lib.datasource.object.jaxb.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (com.gentics.lib.datasource.object.jaxb.ObjectFactory.class));
    public final static java.lang.Class version = (com.gentics.lib.datasource.object.jaxb.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.gentics.lib.datasource.object.jaxb.DefinitionType.class), "com.gentics.lib.datasource.object.jaxb.impl.DefinitionTypeImpl");
        defaultImplementations.put((com.gentics.lib.datasource.object.jaxb.Attributetype.class), "com.gentics.lib.datasource.object.jaxb.impl.AttributetypeImpl");
        defaultImplementations.put((com.gentics.lib.datasource.object.jaxb.Objecttype.class), "com.gentics.lib.datasource.object.jaxb.impl.ObjecttypeImpl");
        defaultImplementations.put((com.gentics.lib.datasource.object.jaxb.Definition.class), "com.gentics.lib.datasource.object.jaxb.impl.DefinitionImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "definition"), (com.gentics.lib.datasource.object.jaxb.Definition.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gentics.lib.datasource.object.jaxb
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of DefinitionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.lib.datasource.object.jaxb.DefinitionType createDefinitionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.lib.datasource.object.jaxb.impl.DefinitionTypeImpl();
    }

    /**
     * Create an instance of Attributetype
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.lib.datasource.object.jaxb.Attributetype createAttributetype()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.lib.datasource.object.jaxb.impl.AttributetypeImpl();
    }

    /**
     * Create an instance of Objecttype
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.lib.datasource.object.jaxb.Objecttype createObjecttype()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.lib.datasource.object.jaxb.impl.ObjecttypeImpl();
    }

    /**
     * Create an instance of Definition
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.gentics.lib.datasource.object.jaxb.Definition createDefinition()
        throws javax.xml.bind.JAXBException
    {
        return new com.gentics.lib.datasource.object.jaxb.impl.DefinitionImpl();
    }

}
