export enum ChipPropertyOptionValueGcmssearch {
    all = 'all',
    broken = 'broken',
    created = 'created',
    edited = 'edited',
    filename = 'filename',
    language = 'language',
    modified = 'modified',
    niceurl = 'niceurl',
    nodeId = 'nodeId',
    online = 'online',
    planned = 'planned',
    published = 'published',
    queued = 'queued',
    template_id = 'template_id',
    objecttype = 'objecttype',
}

export enum ChipPropertyOptionValueElasticsearch {
    all = 'all',
    content = 'content',
    created = 'created',
    creatorId = 'creatorId',
    description = 'description',
    edited = 'edited',
    editorId = 'editorId',
    filename = 'filename',
    id = 'id',
    language = 'language',
    modified = 'modified',
    name = 'name',
    niceUrl = 'niceUrl',
    nodeId = 'nodeId',
    offlineAt = 'offlineAt',
    online = 'online',
    planned = 'planned',
    publishAt = 'publishAt',
    published = 'published',
    publisherId = 'publisherId',
    queued = 'queued',
    queuedOfflineAt = 'queuedOfflineAt',
    queuedPublishAt = 'queuedPublishAt',
    systemCreationDate = 'systemCreationDate',
    systemEditDate = 'systemEditDate',
    templateId = 'templateId',
    customCreationDate = 'customCreationDate',
    customEditDate = 'customEditDate',
    path = 'path',
    objecttype = 'objecttype',
}
